### ISSUE TITLE
TLSv1 not possible as TLS protocol

### ISSUE THREAD

**Issue by KKeXX** [floragunncom/search-guard#650] opened 2019-03-13 15:39 UTC
* Search Guard 6.6.1-24.1 and Elasticsearch 6.6.1
* JVM version Oracle Corporation/Java HotSpot(TM) 64-Bit Server VM/1.8.0_191/25.191-b26 and operating system RHEL 6.10 /2.6.32-754.9.1.el6.x86_64/amd64
* SSL Version 1.0.1e-fips
* netty-tcnative verson  2.0.20.Final-linux-x86_64-fedora.jar
* Number of nodes in your cluster 3

I use Searchguard for authentication and TLS. But I've an old applicaton which only supports TLSv1. I followed the config for [Configuring TLS](https://docs.search-guard.com/latest/configuring-tls) and [OpenSSL setup](https://docs.search-guard.com/latest/openssl).

When I try to use OpenSSL for Security only TLSv1.2 and TLSv1.1 is available. But I've configured TLSv1 as well in elasticsearch.yml:
`searchguard.ssl.http.enabled_ciphers:`
`  - 'TLS_DHE_RSA_WITH_AES_256_CBC_SHA'`
`  - 'TLS_DHE_DSS_WITH_AES_128_CBC_SHA256'`

`searchguard.ssl.http.enabled_protocols:`
`  - 'TLSv1'`
`  - 'TLSv1.1'`
`  - 'TLSv1.2'`

`searchguard.ssl.transport.enabled_ciphers:`
`  - 'TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384'`

`searchguard.ssl.transport.enabled_protocols:`
`  -  'TLSv1.2'`

When Elasticsearch get's startet, TLSv1 is not enabled:
`TLS Transport Client Provider : OPENSSL`
`TLS Transport Server Provider : OPENSSL`
`TLS HTTP Provider             : OPENSSL`
`Enabled TLS protocols for transport layer : [TLSv1.2]`
`Enabled TLS protocols for HTTP layer      : [TLSv1.2, TLSv1.1]`

When I remove the netty-tcnative, JDK is used and TLSv1 is available:
`TLS Transport Client Provider : JDK`
`TLS Transport Server Provider : JDK`
`TLS HTTP Provider             : JDK`
`Enabled TLS protocols for transport layer : [TLSv1.2]`
`Enabled TLS protocols for HTTP layer      : [TLSv1, TLSv1.1, TLSv1.2]`

Is this expected behavior or a bug?

**Comment by floragunncom** [comment] 2019-03-13 15:57
Are you forced to use a FIPS-compliant OpenSSL version?

**Comment by KKeXX** [comment] 2019-03-14 05:49
This is the default OpenSSL Version on RHEL 6:
`openssl version`
`OpenSSL 1.0.1e-fips 11 Feb 2013
It supports TLSv1:`

`openssl s_client -help 2>&1  > /dev/null | egrep "\-(ssl|tls)[^a-z]"`
` -ssl2         - just use SSLv2`
` -ssl3         - just use SSLv3`
` -tls1_2       - just use TLSv1.2`
` -tls1_1       - just use TLSv1.1`
` -tls1         - just use TLSv1`

I upgraded Elasticsearch and SearchGuard yesterday. From ES 5.6.15 with SearchGuard 5.6.15-19.3. OS and JVM did not change.

TLSv1 was possible with this setup (with ES 5.6.15). Here are the Logs before the upgrade:
`Open SSL OpenSSL 1.0.1e-fips 11 Feb 2013 (268439647) available`
`java.version: 1.8.0_191`
`sslTransportClientProvider:OPENSSL with ciphers [TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]`
`sslTransportServerProvider:OPENSSL with ciphers [TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384]`
`sslHTTPProvider:OPENSSL with ciphers [TLS_DHE_RSA_WITH_AES_256_CBC_SHA, TLS_DHE_DSS_WITH_AES_128_CBC_SHA256]`
`sslTransport protocols [TLSv1.2]`
`sslHTTP protocols [TLSv1, TLSv1.1, TLSv1.2]`

**Comment by floragunncom** [comment] 2019-03-14 12:01
From which version (ES+SG) did you upgrade?

**Comment by KKeXX** [comment] 2019-03-14 12:12
As written, I upgraded from ES 5.6.15 with SG 5.6.15-19.3 to ES 6.6.1 with SG6.6.1-24.1

**Comment by floragunncom** [comment] 2019-03-14 12:18
Thanks, will try to reproduce and investigate ...

**Comment by floragunncom** [comment] 2019-03-14 19:44
Seems to be a bug, will be fixed with 24.2 next week ...

**Comment by KKeXX** [comment] 2019-03-15 08:25
Perfect, sounds good!

**Comment by floragunncom** [comment] 2019-03-20 00:29
Fixed with v24.2 released today

**Closed by floragunncom** 2019-03-20 00:29 UTC
Labels: bug

**Comment by KKeXX** [comment] 2019-03-20 06:30
Very good. Just upgraded ES to 6.6.2 ans SG to 6.6.2-24.2 and OpenSSL works as expected.
Thanks!
