### ISSUE TITLE
Search Guard 2 "Not yet initialed" after changing Elasticseach path

### ISSUE THREAD

**Issue by cfoutstd** [floragunncom/search-guard#211] opened 2016-10-04 18:12 UTC
Elasticsearch v2.3.5
Search Guard SSL v2.3.5.15
Search Guard v2.3.5.5

Steps:

- I installed ES, started it, and verified it's running via curl -I http://localhost:9200
- Stopped ES
- Installed SG-SSL, generated key/certs pairs, copied key/certs pairs into /etc/elasticsearch, and configured /etc/elasticsearch.yml to use SSL
- Started ES, and verified it works via SSL by running curl -I --cacerts /path-to-certs/root-ca.pem https://localhost:9200 -u user:pw
- Installed SG, copied sg_*.yml files into /etc/elasticsearch, configured sg_*.yml to work with my setup
- Ran /path/sgadmin.sh with_some_parms
- Restarted ES, and verified it works via curl function above.
- Installed Logstash and Kibana, and verified that I'm seeing indices I set up in Kibana

Here is where I introduce a problem...
- Stopped ES
- Change the data path by setting path.data: /new_data_path in /etc/elasticsearch.yml
- Ensured /new_data_path is accessible by elasticsearch user/group
- Start ES

Now I see 
```
[2016-10-04 18:10:53,948][WARN ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [ip-10-x-x] searchguard index not healthy yet, we try again ... (Reason: timeout)
[2016-10-04 18:10:54,264][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Not yet initialized
[2016-10-04 18:10:56,268][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Not yet initialized
[2016-10-04 18:10:58,272][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Not yet initialized
[2016-10-04 18:11:00,276][ERROR][com.floragunn.searchguard.auth.BackendRegistry] Not yet initialized

```

It's not a permissions issue since I see a /new_data_path/elasticsearch/nodes directory, and subdirs and files in it, created.

I if comment out the path.data line, and restart elasticsearch, it all works again.

**Comment by cfoutstd** [comment] 2016-10-04 18:23
I don't see these lines when I use a different path.data

```
[2016-10-04 18:21:24,750][INFO ][cluster.routing.allocation] [ip-10-22-x-x] Cluster health status changed from [RED] to [YELLOW] (reason: [shards started [[searchguard][0]] ...]).
[2016-10-04 18:21:24,809][INFO ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [ip-10-22-x-x] Node 'ip-10-22-9-4' initialized
```

**Comment by floragunncom** [comment] 2016-10-04 18:31
That's not a bug, it's a expected behavior. Reason is that the configuration is stored in an index (happens when you run sgadmin.sh). When now the data path is changed ES is empty again and you have to initialize via sgadmin.sh again). We also recommend to install v6 (or v7 which will be released today) cause this versions fix bug regarding initialization of Search Guard.

**Closed by floragunncom** 2016-10-04 18:31 UTC

**Comment by cfoutstd** [comment] 2016-10-04 19:24
So the order of events then should be (i'm asking)?

- Change data path
- Run sgadmin.sh
- Restart ES

Thanks
