### ISSUE TITLE
Adding searchguard.ssl.http.clientauth_mode: REQUIRE to elasticsearch.yml file unable to access the cluster

### ISSUE THREAD

**Issue by KSSekhar** [floragunncom/search-guard#494] opened 2018-05-17 14:21 UTC
Search Guard version 6
Elastic Search version 6
JVM version 1.8 
Operating system version CentOs 7
Number of Nodes : 1
Description : Adding searchguard.ssl.http.clientauth_mode: REQUIRE to elasticsearch.yml file unable to access the cluster through browser

URL: https://Ip:9200 with Basic Authentication.

Prevoiusly I am able to access Elastic search through browser with Basic Authentication.After Adding ClientAuth_Mode:REQUIRE to elasticsearch.yml it unable to access and Showing routines:ssl3_get_client_certificate:peer did not return a certificate
elasticssearch.yml

searchguard.enterprise_modules_enabled: false
searchguard.ssl.http.clientauth_mode: REQUIRE

searchguard.ssl.transport.pemcert_filepath: esnode.pem
searchguard.ssl.transport.pemkey_filepath: esnode.key
searchguard.ssl.transport.pemkey_password: dxmdop
searchguard.ssl.transport.pemtrustedcas_filepath: root-ca.pem
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.http.enabled: true
searchguard.ssl.http.pemcert_filepath: esnode.pem
searchguard.ssl.http.pemkey_filepath: esnode.key
searchguard.ssl.http.pemkey_password: dxmdop
searchguard.ssl.http.pemtrustedcas_filepath: root-ca.pem
searchguard.nodes_dn:
- CN=esnode.subexworld.org,C=in, L=Bangalore, O=Subex Ltd
searchguard.authcz.admin_dn:
- CN=roller.subexworld.org,C=in, L=Bangalore, O=Subex Ltd

[sg_config.txt](https://github.com/floragunncom/search-guard/files/2013473/sg_config.txt)
[ElasticSearch.log](https://github.com/floragunncom/search-guard/files/2013477/ElasticSearch.log)
[sg_action_groups.txt](https://github.com/floragunncom/search-guard/files/2013488/sg_action_groups.txt)
[sg_internal_users.txt](https://github.com/floragunncom/search-guard/files/2013489/sg_internal_users.txt)
[sg_roles.txt](https://github.com/floragunncom/search-guard/files/2013490/sg_roles.txt)
[sg_roles_mapping.txt](https://github.com/floragunncom/search-guard/files/2013491/sg_roles_mapping.txt)

**Comment by floragunncom** [comment] 2018-05-17 14:30
"routines:ssl3_get_client_certificate:peer did not return a certificate" is expected with clientauth_mode: REQUIRE if you do not send a client certificate along.

**Comment by jochenkressin** [comment] 2018-05-17 22:11
What are you trying to achieve by setting the TLS client auth mode to "REQUIRE"? The effect of setting this is that you can only access ES/SG when you send a TLS client certificate, hence the wording "REQUIRED". So if you do not add a client certificate thus can't access the cluster, everything is working as expected.

**Comment by KSSekhar** [comment] 2018-05-18 02:10
Giving more security to ES.how to add client certificate to access the cluster.I tried to pass all certificate nothing can be working.Can you please tell what to do in client as well server

Another issue: After installing SG unable to ES cluster from elastic search low level rest client.this client auth mode is disabled.I am getting speaks http plaintext instead of ssl, will close the channel in Cluster side.

**Comment by floragunncom** [comment] 2018-05-18 07:10
This is not a bug, will close this one therefore.

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations:

* Search Guard and Elasticsearch version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug

These informations are optional but are very valueable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Closed by floragunncom** 2018-05-18 07:10 UTC
