### ISSUE TITLE
HTTP 500 instead of 401 on wrong password

### ISSUE THREAD

**Issue by bitmelt** [floragunncom/search-guard#7] opened 2015-06-08 15:45 UTC
I configured the plugin following the instructions, with just the basic roles - `admin` role has access to everything, no other roles configured.

    curl -XPUT 'http://localhost:9200/searchguard/ac/ac' -d '{
       "acl":[
          {
             "__Comment__":"By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
             "filters_bypass":[],
             "filters_execute":[]
          },
          {
             "__Comment__":"For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
             "roles":["admin"],
             "filters_bypass":["*"],
             "filters_execute":[]
          }
       ]
    }'

I then configured the users as follows in `config/elasticsearch.yml`:

    searchguard.authentication.settingsdb.user.admin: changeme
    searchguard.authentication.authorization.settingsdb.roles.admin: ["admin"]

If I make a request to ES without HTTP Basic authentication, then I correctly get back an HTTP 401 status code.  If I make a request to ES with the correct username and password, I get HTTP 200 and the result back as expected:

    curl -i -u 'admin:changeme' -XGET 'http://localhost:9200/megacorp/employee/_search

However, if I pass the wrong password, the server throws an exception and returns a 500 instead of a 401 that I would expect with the wrong password:

    curl -i -u 'admin:wrong' -XGET 'http://localhost:9200/megacorp/employee/_search

    HTTP/1.1 500 Internal Server Error
    Content-Type: application/json; charset=UTF-8
    Content-Length: 239
    
    {
      "error" : "AuthException[com.floragunn.searchguard.authentication.AuthException: No user admin or wrong password (digest: plain/none)]; nested: AuthException[No user admin or wrong password (digest: plain/none)]; ",
      "status" : 500
    }

The exception in the log is:

    [2015-06-08 11:25:18,060][ERROR][com.floragunn.searchguard.authentication.backend.GuavaCachingAuthenticationBackend] java.util.concurrent.ExecutionException: com.floragunn.searchguard.authentication.AuthException: No user admin or wrong password (digest: plain/none)
    java.util.concurrent.ExecutionException: com.floragunn.searchguard.authentication.AuthException: No user admin or wrong password (digest: plain/none)
    	at org.elasticsearch.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
    	at org.elasticsearch.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
    	at org.elasticsearch.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
    	at org.elasticsearch.common.util.concurrent.Uninterruptibles.getUninterruptibly(Uninterruptibles.java:137)
    	at org.elasticsearch.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2348)
    	at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
    	at org.elasticsearch.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
    	at org.elasticsearch.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
    	at org.elasticsearch.common.cache.LocalCache.get(LocalCache.java:3937)
    	at org.elasticsearch.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
    	at org.elasticsearch.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
    	at com.floragunn.searchguard.authentication.backend.GuavaCachingAuthenticationBackend.authenticate(GuavaCachingAuthenticationBackend.java:65)
    	at com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator.authenticate(HTTPBasicAuthenticator.java:77)
    	at com.floragunn.searchguard.rest.AbstractACRestFilter.process(AbstractACRestFilter.java:178)
    	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:283)
    	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:180)
    	at org.elasticsearch.http.HttpServer.internalDispatchRequest(HttpServer.java:121)
    	at org.elasticsearch.http.HttpServer$Dispatcher.dispatchRequest(HttpServer.java:83)
    	at org.elasticsearch.http.netty.NettyHttpServerTransport.dispatchRequest(NettyHttpServerTransport.java:329)
    	at org.elasticsearch.http.netty.HttpRequestHandler.messageReceived(HttpRequestHandler.java:63)
    	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    	at org.elasticsearch.http.netty.pipelining.HttpPipeliningHandler.messageReceived(HttpPipeliningHandler.java:60)
    	at org.elasticsearch.common.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:88)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    	at org.elasticsearch.common.netty.handler.codec.http.HttpChunkAggregator.messageReceived(HttpChunkAggregator.java:145)
    	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    	at org.elasticsearch.common.netty.handler.codec.http.HttpContentDecoder.messageReceived(HttpContentDecoder.java:108)
    	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:296)
    	at org.elasticsearch.common.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:459)
    	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.callDecode(ReplayingDecoder.java:536)
    	at org.elasticsearch.common.netty.handler.codec.replay.ReplayingDecoder.messageReceived(ReplayingDecoder.java:435)
    	at org.elasticsearch.common.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
    	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:74)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
    	at org.elasticsearch.common.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
    	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:268)
    	at org.elasticsearch.common.netty.channel.Channels.fireMessageReceived(Channels.java:255)
    	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
    	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
    	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
    	at org.elasticsearch.common.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
    	at org.elasticsearch.common.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
    	at org.elasticsearch.common.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
    	at org.elasticsearch.common.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
    	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    	at java.lang.Thread.run(Thread.java:745)
    Caused by: com.floragunn.searchguard.authentication.AuthException: No user admin or wrong password (digest: plain/none)
    	at com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend.authenticate(SettingsBasedAuthenticationBackend.java:80)
    	at com.floragunn.searchguard.authentication.backend.GuavaCachingAuthenticationBackend$1.load(GuavaCachingAuthenticationBackend.java:50)
    	at com.floragunn.searchguard.authentication.backend.GuavaCachingAuthenticationBackend$1.load(GuavaCachingAuthenticationBackend.java:46)
    	at org.elasticsearch.common.cache.LocalCache$LoadingValueReference.loadFuture(LocalCache.java:3527)
    	at org.elasticsearch.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2319)
    	... 51 more

**Comment by floragunncom** [comment] 2015-06-25 13:10
Confirmed as a bug

**Comment by vipulvkp** [comment] 2016-01-11 10:14
Thanks for confirming this as a bug. I am also constantly getting this error while setting up the acl rules.
Can you please tell us is any workaround is available or if the fix is released.

**Comment by floragunncom** [comment] 2016-05-01 11:08
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Closed by floragunncom** 2016-05-01 11:08 UTC
Labels: bug
