### ISSUE TITLE
How to implement REST layer SSL?

### ISSUE THREAD

**Issue by LinhTruongVan** [floragunncom/search-guard#26] opened 2015-07-01 07:53 UTC
@floragunncom ,
I created some files: SearchGuardKS.jdk, SearchGuardTK.jdk, SearchGuardKS.pem,.. with Java Keytools. Then in elasticsearch.yml file, i edited some lines following:

searchguard.ssl.transport.http.enabled: true
searchguard.ssl.transport.http.keystore_type: JKS
searchguard.ssl.transport.http.keystore_filepath: D:\keys\SearchguardKS.jks
searchguard.ssl.transport.http.keystore_password: changeit

searchguard.ssl.transport.http.enforce_clientauth: true
searchguard.ssl.transport.http.truststore_type: JKS
searchguard.ssl.transport.http.truststore_filepath: D:\keys\SearchguardTS.jks
searchguard.ssl.transport.http.truststore_password: changeit

After that, i can't connect to Elasticsearch, i got a message:
"The connection to 'localhost' failed.  <br />System.Security.SecurityException Failed to negotiate HTTPS connection with server.fiddler.network.https&gt; HTTPS handshake to localhost (for #152) failed. System.Security.Authentication.AuthenticationException A call to SSPI failed, see inner exception. &lt; An unknown error occurred while processing the certificate Win32 (SChannel) Native Error Code: 0x80090327 ". 

So i don't know how to do next to implement REST layer SSL with Search-guard. Can you help me?

Thanks you

**Comment by floragunncom** [comment] 2015-07-01 13:06
1) How did you create the key files? Pls have a look into https://github.com/floragunncom/search-guard/tree/master/example-pki-scripts

2) Monitoring https connections with fiddler is possible but please make sure first that a normal connection from the browser is working with fiddler (and other tools like that) turned off.

**Comment by LinhTruongVan** [comment] 2015-07-02 01:36
Hi @floragunncom,
I'm .NET developer so i don't good about Java, keytool. I run "example.sh" from  https://github.com/floragunncom/search-guard/tree/master/example-pki-scripts , then i got some files such as: node-0-keystore.jsk,  node-1-keystore.jsk,  node-2-keystore.jsk, truststore.jsk.I also got some directories: ca, certs, crl.
But i don't know how to do next. Which file we will use in elasticsearch.yml configure?
I tried using following config and its not working:
searchguard.ssl.transport.http.enabled: true
searchguard.ssl.transport.http.keystore_type: JKS
searchguard.ssl.transport.http.keystore_filepath: ...\node-0-keystore.jks
searchguard.ssl.transport.http.keystore_password: kspass

searchguard.ssl.transport.http.enforce_clientauth: true
searchguard.ssl.transport.http.truststore_type: JKS
searchguard.ssl.transport.http.truststore_filepath: ...\truststore.jks
searchguard.ssl.transport.http.truststore_password: tspass

**Comment by floragunncom** [comment] 2015-07-03 12:48
pls look here https://github.com/floragunncom/search-guard/blob/es1.6/src/test/java/com/floragunn/searchguard/SslTest.java <code>mutualSSLAuthentication()</code> and this may help too http://stackoverflow.com/questions/4421536/java-ssl-clientside-authentication-with-self-signed-certificates
 and http://stackoverflow.com/questions/19486200/is-there-a-way-to-test-2-way-ssl-through-browser

2-way (or mutual) ssl authentication means that not only the client (browser) trusts the server, it means also that the server trusts the client and knows how the client is. so the client public certificate has to be in the truststore of the server, and the servers certificate needs to be trusted by the client (browser) - typically by using a root certificate/CA, pls have a look also into https://github.com/floragunncom/search-guard/tree/master/example-pki-scripts how to setup key- and truststore properly with a root certificate/root ca.

This is also a good source of information: https://www.elastic.co/guide/en/shield/current/certificate-authority.html and https://www.elastic.co/guide/en/shield/current/ssl-tls.html

**Comment by LinhTruongVan** [comment] 2015-07-09 06:06
Hi @floragunncom ,
I created keys with :  https://github.com/floragunncom/search-guard/tree/master/example-pki-scripts , but  is'nt working.

**Comment by floragunncom** [comment] 2015-07-10 13:14
cannot reproduce this, maybe its windows related. how do you execute the scripts on windows? cygwin?
Maybe somebody else can try this on windows and report back if it working.

**Comment by dsvetlov** [comment] 2016-03-04 10:14
Has same problem on linux. Just replace jdk with p12 store and it stars work.

**Comment by floragunncom** [comment] 2016-05-01 11:11
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Closed by floragunncom** 2016-05-01 11:11 UTC
Labels: help wanted
