### ISSUE TITLE
[search-guard-ssl] is incompatible with Elasticsearch [2.3.5]

### ISSUE THREAD

**Issue by bujarmetaj2016** [floragunncom/search-guard#192] opened 2016-08-04 13:56 UTC
"Exception in thread \"main\" java.lang.IllegalArgumentException: Plugin [search-guard-ssl] is incompatible with Elasticsearch [2.3.5]. Was designed for version [2.3.4]

**Comment by floragunncom** [comment] 2016-08-04 20:29
Duplicate of https://github.com/floragunncom/search-guard-ssl/issues/30

**Closed by floragunncom** 2016-08-04 20:29 UTC
