### ISSUE TITLE
Discuss about searchguard.authentication.settingsdb.digest

### ISSUE THREAD

**Issue by LinhTruongVan** [floragunncom/search-guard#28] opened 2015-07-03 10:10 UTC
Hi @floragunncom ,
I'm facing with some troubles when implement searchguard.authentication.settingsdb.digest .
I configured following:
"searchguard.authentication.settingsdb.digest: SHA1
searchguard.authentication.settingsdb.user.guest: 35675e68f4b5af7b995d9205ad0fc43842f16450 (the "guest" after hash with SHA1) "
Then i requested " curl -XGET 'http://guest:guest@localhost:9200/' "  OR " curl -XGET 'http://guest:35675e68f4b5af7b995d9205ad0fc43842f16450@localhost:9200/' " , i got error "AuthException[com.floragunn.searchguard.authentication.AuthException".

But when i configured:
"searchguard.authentication.settingsdb.digest: SHA1
searchguard.authentication.settingsdb.user.guest: guest "
Then i requested " curl -XGET 'http://guest:35675e68f4b5af7b995d9205ad0fc43842f16450@localhost:9200/' " . I got good data.

Could you explain me why? Why in elasticsearch.yml , we save clear password instead of hashed password.

**Comment by floragunncom** [comment] 2015-07-03 12:31
duplicate of https://github.com/floragunncom/search-guard/issues/24

**Closed by floragunncom** 2015-07-03 12:31 UTC
