### ISSUE TITLE
Cannot configure searchguard-2.3.3 with sgadmin.sh

### ISSUE THREAD

**Issue by gdoucet-fr** [floragunncom/search-guard#136] opened 2016-06-07 14:32 UTC
Hello,

I have been using Search Guard for elasticsearch 2.3.1 successfully with users roles and all.
I updated to elasticsearch 2.3.3 and so I downloaded SG, and I cannot seem to initialize SG with sgadmin.sh.
The error logs are the followings :

Exception in thread "main" NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{127.0.0.1}{localhost/127.0.0.1:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:154)

And in the elasticsearch console I get this error from searchguard:

[com.floragunn.searchguard.transport.SearchGuardTransportService] No user found in this class org.elasticsearch.action.admin.cluster.node.liveness.LivenessRequest for action cluster:monitor/nodes/liveness and transport type netty.

This reminds me of issue #98, I googled around but I don't have any clue...

Thanks in advance

**Comment by floragunncom** [comment] 2016-06-07 14:52
How many nodes do you have in your cluster? 
Are **all** nodes running with ES 2.3.3 and SG beta 3 and SG SSL 2.3.3.10 ?

**Comment by gdoucet-fr** [comment] 2016-06-07 15:09
I have just one node in the cluster running with ES 2.3.3, and SG beta 3 and SG SSL 2.3.3.10

I did a full install from scratch several times to be sure. And to rule out the keystore/truststore certificate issues, I use the same that I am using with ES 2.3.1, SG beta 1 and SG SSL 2.3.1.8 which stills works fine :)

**Comment by floragunncom** [comment] 2016-06-07 15:44
seem you use a node (instead of a client certificate) certificate for sgadmin. Can you post you elasticsearch.yml pls?

**Comment by gdoucet-fr** [comment] 2016-06-07 15:46
There it is :

# ======================== Elasticsearch Configuration =========================
#
# NOTE: Elasticsearch comes with reasonable defaults for most settings.
#       Before you set out to tweak and tune the configuration, make sure you
#       understand what are you trying to accomplish and the consequences.
#
# The primary way of configuring a node is via this file. This template lists
# the most important settings you may want to configure for a production cluster.
#
# Please see the documentation for further information on configuration options:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/setup-configuration.html>
#
# ---------------------------------- Cluster -----------------------------------
#
# Use a descriptive name for your cluster:
#
cluster.name: ssci-stats
#
# ------------------------------------ Node ------------------------------------
#
# Use a descriptive name for the node:
#
node.name: node-1
#
# Add custom attributes to the node:
#
# node.rack: r1
#
# ----------------------------------- Paths ------------------------------------
#
# Path to directory where to store the data (separate multiple locations by comma):
path.data: /home/gdoucet/Documents/elasticsearch-2.3.3/data
#
# Path to log files:
path.logs: /home/gdoucet/Documents/elasticsearch-2.3.3/logs
#
# ----------------------------------- Memory -----------------------------------
#
# Lock the memory on startup:
#
# bootstrap.mlockall: true
#
# Make sure that the `ES_HEAP_SIZE` environment variable is set to about half the memory
# available on the system and that the owner of the process is allowed to use this limit.
#
# Elasticsearch performs poorly when the system is swapping the memory.
#
# ---------------------------------- Network -----------------------------------
#
# Set the bind address to a specific IP (IPv4 or IPv6):
#
network.host: 127.0.0.1
#
# Set a custom port for HTTP:
#
http.port: 9200
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-network.html>
#
# --------------------------------- Discovery ----------------------------------
#
# Pass an initial list of hosts to perform discovery when new node is started:
# The default list of hosts is ["127.0.0.1", "[::1]"]
#
discover.zen.ping.multicast.enabled: false
#
# discovery.zen.ping.unicast.hosts: ["host1", "host2"]
#
# Prevent the "split brain" by configuring the majority of nodes (total number of nodes / 2 + 1):
#
# discovery.zen.minimum_master_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-discovery.html>
#
# ---------------------------------- Gateway -----------------------------------
#
# Block initial recovery after a full cluster restart until N nodes are started:
#
# gateway.recover_after_nodes: 3
#
# For more information, see the documentation at:
# <http://www.elastic.co/guide/en/elasticsearch/reference/current/modules-gateway.html>
#
# ---------------------------------- Various -----------------------------------
#
# Disable starting multiple nodes on a single system:
#
# node.max_local_storage_nodes: 1
#
# Require explicit names when deleting indices:
#
# action.destructive_requires_name: true
#
# ---------------------------------- Search Guard SSL ----------------------------
#                                   Transport layer SSL                          
#
# Enable or disable node-to-node ssl encryption (default: true)
searchguard.ssl.transport.enabled: true
#
# JKS or PKCS12 (default: JKS)
searchguard.ssl.transport.keystore_type: JKS
#
# Relative path to the keystore file (mandatory, this stores the server certificates), must be placed under the config/ dir
searchguard.ssl.transport.keystore_filepath: /home/gdoucet/Documents/res/searchguard/keystore.jks
#
# Alias name (default: first alias which could be found)
searchguard.ssl.transport.keystore_alias: "localhost"
#
# Keystore password (default: changeit)
searchguard.ssl.transport.keystore_password: "changeit"
#
# JKS or PKCS12 (default: JKS)
searchguard.ssl.transport.truststore_type: JKS
#
# Relative path to the truststore file (mandatory, this stores the client/root certificates), must be placed under the config/ dir
searchguard.ssl.transport.truststore_filepath: /home/gdoucet/Documents/res/searchguard/truststore.jks
#
# Alias name (default: first alias which could be found)
searchguard.ssl.transport.truststore_alias: "localhost"
#
# Truststore password (default: changeit)
searchguard.ssl.transport.truststore_password: "changeit"
#
# Enforce hostname verification (default: true)
searchguard.ssl.transport.enforce_hostname_verification: false
# If hostname verification specify if hostname should be resolved (default: true)
#searchguard.ssl.transport.resolve_hostname: true
# Use native Open SSL instead of JDK SSL if available (default: true)
#searchguard.ssl.transport.enable_openssl_if_available: false

#############################################################################################
# HTTP/REST layer SSL                                                                       #
#                                                                                           #
#############################################################################################
# Enable or disable rest layer security - https, (default: false)
#searchguard.ssl.http.enabled: true
# JKS or PKCS12 (default: JKS)
#searchguard.ssl.http.keystore_type: PKCS12
# Relative path to the keystore file (this stores the server certificates), must be placed under the config/ dir
#searchguard.ssl.http.keystore_filepath: keystore_https_node1.jks
# Alias name (default: first alias which could be found)
#searchguard.ssl.http.keystore_alias: my_alias
# Keystore password (default: changeit)
#searchguard.ssl.http.keystore_password: changeit
# Do the clients (typically the browser or the proxy) have to authenticate themself to the http server, default is OPTIONAL
# To enforce authentication use REQUIRE, to completely disable client certificates use NONE
#searchguard.ssl.http.clientauth_mode: REQUIRE
# JKS or PKCS12 (default: JKS)
#searchguard.ssl.http.truststore_type: PKCS12
# Relative path to the truststore file (this stores the client certificates), must be placed under the config/ dir
#searchguard.ssl.http.truststore_filepath: truststore_https.jks
# Alias name (default: first alias which could be found)
#searchguard.ssl.http.truststore_alias: my_alias
# Truststore password (default: changeit)
#searchguard.ssl.http.truststore_password: changeit
# Use native Open SSL instead of JDK SSL if available (default: true)
#searchguard.ssl.http.enable_openssl_if_available: false

security.manager.enabled: false
searchguard.authcz.admin_dn:
  - "CN=localhost,OU=Kiosk,O=Amadeus,L=Nice,C=FR"

**Comment by floragunncom** [comment] 2016-06-07 16:01
```
searchguard.authcz.admin_dn:
  - "CN=localhost,OU=Kiosk,O=Amadeus,L=Nice,C=FR"
```

As i guessed this is a node certificate, but it should be a client certificate like "CN=gdoucet,OU=people,O=Amadeus,L=Nice,C=FR" or something like that
and must not contain [oid:1.2.3.4.5.5](https://github.com/floragunncom/search-guard/wiki/What-means-oid:1.2.3.4.5.5)

See https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/gen_client_node_cert.sh

**Comment by gdoucet-fr** [comment] 2016-06-07 16:05
Ok, I will try with that and report back, thanks ! :)

**Comment by gdoucet-fr** [comment] 2016-06-08 11:50
Yeah, sorry for that, kind of work when you read the doc... ^^

**Comment by floragunncom** [comment] 2016-06-09 14:56
can you close this issue if its resolved?

**Closed** 2016-06-09 16:02 UTC
Labels: wait for user feedback

**Comment by yogiGueta** [comment] 2016-08-04 14:16
Hi 
I need some help please. I am getting the same error: 
ERR: Cannot connect to elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{“some-ip”}{“some-ip”:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:259)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:72)

I have got a docker container of Elasticsearch version (2.3.3), another one of Kibana and another of Logstash.
What I’m trying to do now is to make user privilege: I want only “admin” can access to security logs in Elasticsearch, and only “yogi” can access to debug logs etc. 
I am running only one node name: goby and two users: admin and yogi. 
I tried to follow the instruction in https://github.com/floragunncom/search-guard, but I did not succeed.
Can you tell me please what to do? Or what I did wrong?

1.	I install both of the plugins:  search-guard-ssl (version 2.3.3.14), search-guard-2(2.3.3.3).

2.	I ran the script example.sh with the following changes:
#!/bin/bash
set -e
./clean.sh
./gen_root_ca.sh capass changeit
./gen_node_cert.sh goby changeit capass
./gen_client_node_cert.sh admin changeit capass
./gen_client_node_cert.sh yogi changeit capass

3.	My  elasticsearch.yml:

cluster.name: mycluster
node.master: true
node.data: true
discovery.zen.ping.multicast.enabled: false
number_of_nodes : 1
minimum_master_nodes: 1
path.logs: .
node.name: ElasticStack.${IP}
network.publish_host: ${IP}
network.bind_host: "0.0.0.0"
searchguard.ssl.transport.enabled: true
searchguard.ssl.transport.keystore_filepath: /usr/share/elasticsearch/config/yogi-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: /usr/share/elasticsearch/config/truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.http.clientauth_mode: REQUIRE

searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: /usr/share/elasticsearch/config/yogi-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: /usr/share/elasticsearch/config/truststore.jks
searchguard.ssl.http.truststore_password: changeit

searchguard.authcz.admin_dn:
  - "CN=yogi,OU=client,O=client,L=Test, C=DE"
  - "CN=node-goby, OU=SSL, O=Test, L=Test, C=DE"

4. In Elasticsearch/config path: I added the files (created by the example.sh):
node-goby-keystore.jks
yogi-keystore.jks
admin-keystore.jks
truststore.jks

5. now Kibana section:

6. my kibana.yml: 

# Kibana is served by a back end server. This controls which port to use.
port: 5601

# The host to bind the server to.
host: "0.0.0.0"

# The Elasticsearch instance to use for all your queries.
elasticsearch_url: https://elastic-ip”:9200"

# preserve_elasticsearch_host true will send the hostname specified in `elasticsearch`. If you set it to false,
# then the host you use to connect to *this* Kibana instance will be sent.
elasticsearch_preserve_host: true

# Kibana uses an index in Elasticsearch to store saved searches, visualizations
# and dashboards. It will create a new index if it doesn't already exist.
kibana_index: ".kibana"

# If your Elasticsearch is protected with basic auth, this is the user credentials
# used by the Kibana server to perform maintence on the kibana_index at statup. Your Kibana
# users will still need to authenticate with Elasticsearch (which is proxied thorugh
# the Kibana server)
kibana_elasticsearch_username: "paas"
kibana_elasticsearch_password: "kibanaserver"

# If your Elasticsearch requires client certificate and key
# kibana_elasticsearch_client_crt: /path/to/your/client.crt
# kibana_elasticsearch_client_key: /path/to/your/client.key

# If you need to provide a CA certificate for your Elasticsarech instance, put
# the path of the pem file here.
ca: /config/root-ca.pem (I put it there)

# The default application to load.
default_app_id: "dashboard/desh2"

# Time in milliseconds to wait for elasticsearch to respond to pings, defaults to
# request_timeout setting
# ping_timeout: 1500

# Time in milliseconds to wait for responses from the back end or elasticsearch.
# This must be > 0
request_timeout: 300000

# Time in milliseconds for Elasticsearch to wait for responses from shards.
# Set to 0 to disable.
shard_timeout: 0

# Time in milliseconds to wait for Elasticsearch at Kibana startup before retrying
# startup_timeout: 5000

# Set to false to have a complete disregard for the validity of the SSL
# certificate.
verify_ssl: true

# SSL for outgoing requests from the Kibana Server (PEM formatted)
# ssl_key_file: /path/to/your/server.key
# ssl_cert_file: /path/to/your/server.crt

# Set the path to where you would like the process id file to be created.
# pid_file: /var/run/kibana.pid

# If you would like to send the log output to a file you can set the path below.
# This will also turn off the STDOUT log output.
# log_file: ./kibana.log
# Plugins that are included in the build, and no longer found in the plugins/ folder
bundled_plugin_ids:
 - plugins/dashboard/index
 - plugins/discover/index
 - plugins/doc/index
 - plugins/kibana/index
 - plugins/markdown_vis/index
 - plugins/metric_vis/index
 - plugins/settings/index
 - plugins/table_vis/index
 - plugins/vis_types/index
 - plugins/visualize/index


6. I added sg_roles.yml to elasticsearch/plugins/search-guard-2/sgconfig path with:
sg_kibana4_server:
  cluster:
      - cluster:monitor/nodes/info
      - cluster:monitor/health
  indices:
    '?kibana':
      '*':
        - "indices:*"
7. I added sg_roles_mapping.yml to elasticsearch/plugins/search-guard-2/sgconfig path with:
sg_kibana4_server:
  users:
    - paas

8. I added sg_internal_users.yml to elasticsearch/plugins/search-guard-2/sgconfig path with:
paas:
  hash: $2a$12$4AcgAt3xwOWadA5s5blL6ev39OXDNhmOesEoo33eZtrq2N0YrU3H.
  #password is: kibanaserver

9. I added sg_config.yml to elasticsearch/plugins/search-guard-2/sgconfig path with:
searchguard:
  dynamic:
    http:
     ...
    authc:
      kibana_auth_domain: 
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          challenge: true
        authentication_backend:
          type: internal
    authz:
      ...

10. Applying these settings (in sgadmin path): 
./sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -h ${IP} -ks /usr/share/elasticsearch/config/yogi-keystore.jks -ts /usr/share/elasticsearch/config/truststore.jks  -nhnv

Now I’m getting:


ERR: Cannot connect to elasticsearch. Please refer to elasticsearch logfile for more information
Trace:
NoNodeAvailableException[None of the configured nodes are available: [{#transport#-1}{“some-ip”}{“some-ip”:9300}]]
	at org.elasticsearch.client.transport.TransportClientNodesService.ensureNodesAreAvailable(TransportClientNodesService.java:290)
	at org.elasticsearch.client.transport.TransportClientNodesService.execute(TransportClientNodesService.java:207)
	at org.elasticsearch.client.transport.support.TransportProxyClient.execute(TransportProxyClient.java:55)
	at org.elasticsearch.client.transport.TransportClient.doExecute(TransportClient.java:288)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:359)
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:348)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.execute(AbstractClient.java:848)
	at org.elasticsearch.client.support.AbstractClient$ClusterAdmin.health(AbstractClient.java:868)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main0(SearchGuardAdmin.java:259)
	at com.floragunn.searchguard.tools.SearchGuardAdmin.main(SearchGuardAdmin.java:72)

What did I do wrong?

Thanks!!!!

**Comment by floragunncom** [comment] 2016-08-04 14:44
try 

<pre>./sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -h ${IP} -ks /usr/share/elasticsearch/config/yogi-keystore.jks -ts /usr/share/elasticsearch/config/truststore.jks -nhnv -cn mycluster</pre>

or

<pre>./sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -h ${IP} -ks /usr/share/elasticsearch/config/yogi-keystore.jks -ts /usr/share/elasticsearch/config/truststore.jks -nhnv -icl</pre>

**Comment by yogiGueta** [comment] 2016-08-07 07:50
Hi!
Thanks for the replay! I tried it and it work fine now! But i have other issues now:
When I enter Kibana UI:
1.	There are no HTTP basic auth dialog pops up: 
I set challenge in sg_config.yml to true:
sg_config.yml:
searchguard:
  dynamic:
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: false
        internalProxies: '192\.168\.0\.10|192\.168\.0\.11' # regex pattern
        #internalProxies: '.*' # trust all internal proxies, regex pattern
        remoteIpHeader:  'x-forwarded-for'
        proxiesHeader:   'x-forwarded-by'
        #trustedProxies: '.*' # trust all external proxies, regex pattern
        ###### see https://docs.oracle.com/javase/7/docs/api/java/util/regex/Pattern.html for regex help
        ###### more information about XFF https://en.wikipedia.org/wiki/X-Forwarded-For
        ###### and here https://tools.ietf.org/html/rfc7239
        ###### and https://tomcat.apache.org/tomcat-8.0-doc/config/valve.html#Remote_IP_Valve
    authc:
      kibana_auth_domain: 
        enabled: true
        order: 1
        http_authenticator:
          type: basic
          **challenge: true**
        authentication_backend:
          type: internal
    authz:    
      roles_from_myldap:
        enabled: false
        authorization_backend:
          # LDAP authorization backend (gather roles from a LDAP or Active Directory, you have to configure the above LDAP authentication backend settings too)
          type: ldap # NOT FREE FOR COMMERCIAL USE
          config:
            # enable ldaps
            enable_ssl: false
            # enable start tls, enable_ssl should be false
            enable_start_tls: false
            # send client certificate
            enable_ssl_client_auth: false
            # verify ldap hostname
            verify_hostnames: true
            hosts:
              - localhost:8389
            bind_dn: null
            password: null
            rolebase: 'ou=groups,dc=example,dc=com'
            # Filter to search for roles (currently in the whole subtree beneath rolebase)
            # {0} is substituted with the DN of the user
            # {1} is substituted with the username 
            # {2} is substituted with an attribute value from user's directory entry, of the authenticated user. Use userroleattribute to specify the name of the attribute            
            rolesearch: '(uniqueMember={0})'
            # Specify the name of the attribute which value should be substituted with {2} above
            userroleattribute: null
            # Roles as an attribute of the user entry
            userrolename: memberOf
            # The attribute in a role entry containing the name of that role
            rolename: cn
            # Resolve nested roles transitive (roles which are members of other roles and so on ...)
            resolve_nested_roles: true
            
            userbase: 'ou=people,dc=example,dc=com'
            # Filter to search for users (currently in the whole subtree beneath userbase)
            # {0} is substituted with the username 
            usersearch: '(uid={0})'
            
      roles_from_another_ldap:
        enabled: false
        authorization_backend:
          type: ldap # NOT FREE FOR COMMERCIAL USE
          #config goes here ...
2.	Kibana status is Red: 
plugin:elasticsearch	 Unable to connect to Elasticsearch at https://”ip”:9200.
What to do next?
Thanks!

**Comment by yogiGueta** [comment] 2016-08-07 08:27
the elasticsearch logs:
[2016-08-07 08:22:39,559][ERROR][com.floragunn.searchguard.transport.SearchGuardTransportService] Internal or shard requests not allowed from a non-server node for transport type netty
[2016-08-07 08:22:39,563][WARN ][discovery.zen.ping.unicast] [ElasticStack."ip"] failed to send ping to [{#zen_unicast_1#}{127.0.0.1}{127.0.0.1:9300}]
RemoteTransportException[[ElasticStack."ip"][127.0.0.1:9300][internal:discovery/zen/unicast]]; nested: ElasticsearchSecurityException[Internal or shard requests not allowed from a non-server node for transport type netty];
Caused by: ElasticsearchSecurityException[Internal or shard requests not allowed from a non-server node for transport type netty]
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:201)

**Comment by yogiGueta** [comment] 2016-08-07 08:31
[2016-08-07 08:22:58,008][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [ElasticStack."ip" Someone speaks plaintext instead of ssl, will close the channel
[2016-08-07 08:22:58,015][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [ElasticStack."ip"] Someone speaks plaintext instead of ssl, will close the channel
[2016-08-07 08:22:58,024][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [ElasticStack."ip"] Someone speaks plaintext instead of ssl, will close the channel
[2016-08-07 08:22:58,029][WARN ][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [ElasticStack."ip"] Someone speaks plaintext instead of ssl, will close the channel
[2016-08-07 08:22:58,462][ERROR][com.floragunn.searchguard.http.SearchGuardHttpServerTransport] [ElasticStack."ip"] SSL Problem null cert chain
javax.net.ssl.SSLHandshakeException: null cert chain
	at sun.security.ssl.Handshaker.checkThrown(Handshaker.java:1431)
	at sun.security.ssl.SSLEngineImpl.checkTaskThrown(SSLEngineImpl.java:535)
