### ISSUE TITLE
logstash 5.1 output data with 403 error no permissions for indices:admin/create

### ISSUE THREAD

**Issue by robertchen** [floragunncom/search-guard#290] opened 2017-02-06 17:05 UTC
Issue:  A lot of 403 errors,  a sample one:
<pre>
[2017-02-06T11:52:26,859][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>403, :action=>["index", {:_id=>nil, :_index=>"mycompany-webapps-2017.02.06", :_type=>"webapps", :_routing=>nil}, 2017-02-06T21:52:22.292Z ip-10-8-8-249 2017-02-06 16:52:22,292 [http-nio-8080-exec-14] INFO  com.mycompany.common.db.DBConnectionPool - Pool: default [15, 0, 1] return PoolableConnection@37488347 time=0 ms], :response=>{"index"=>{"_index"=>"mycompany-webapps-2017.02.06", "_type"=>"webapps", "_id"=>nil, "status"=>403, "error"=>{"type"=>"security_exception", "reason"=>"no permissions for indices:admin/create"}}}}
</pre>

Search Guard and Elasticsearch version
Both are 5.1.1
JVM version and operating system version
JDK 1.8, AWS linux
Number of nodes in your cluster
3
<pre>
logstash config:
output {
  stdout { codec => rubydebug }
  elasticsearch {
     hosts => ['10.8.8.246:9200', '10.8.8.209:9200', '10.8.8.248:9200']
     user => "logstash"
     password => "logstash"
     ssl => true
     ssl_certificate_verification => false
     truststore => "/etc/logstash/truststore.jks"
     truststore_password => changeit
     index => "mycompany-%{type}-%{+YYYY.MM.dd}"
  }
}
</pre>

sg_roles.yml has been updated on all 3 nodes and restarted elasticsearch with:
<pre>
sg_logstash:
  cluster:
    - indices:admin/template/get
    - indices:admin/template/put
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    '*':
      '*':
        - '*'
</pre>

<pre>
On elasticsearch, the log shows:
[2017-02-06T17:06:06,856][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=logstash, roles=[]] [IndexType [index=mycompany-webapps-2017.02.06, type=*]] [Action [indices:admin/create]] [RolesChecked [sg_logstash, sg_own_index, sg_public]]
</pre>

**Comment by floragunncom** [comment] 2017-02-06 18:46
I cannot reproduce this.

Can you post your logs (on ES side) on DEBUG level?

**Comment by robertchen** [comment] 2017-02-06 18:55
Seems no much logs on ES side:
ed [sg_logstash, sg_own_index, sg_public]]
[2017-02-06T18:53:11,235][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=logstash, roles=[]] [IndexType [index=mycompany-webapps-2017.02.06, type=*]] [Action [indices:admin/create]] [RolesChecked [sg_logstash, sg_own_index, sg_public]]

A lot of 403 logs in logstash log:
[2017-02-06T13:54:21,244][WARN ][logstash.outputs.elasticsearch] Failed action. {:status=>403, :action=>["index", {:_id=>nil, :_index=>"mycompany-webapps-2017.02.06", :_type=>"webapps", :_routing=>nil}, 2017-02-06T23:54:17.839Z ip-10-8-8-249 2017-02-06 18:54:17,839 [http-nio-8080-exec-14] INFO  com.mycompany.common.db.DBConnectionPool - Pool: default [15, 0, 1] return PoolableConnection@37488347 time=0 ms], :response=>{"index"=>{"_index"=>"mycompany-webapps-2017.02.06", "_type"=>"webapps", "_id"=>nil, "status"=>403, "error"=>{"type"=>"security_exception", "reason"=>"no permissions for indices:admin/create"}}}}

**Comment by floragunncom** [comment] 2017-02-06 18:57
You must enable DEBUG log level

**Comment by robertchen** [comment] 2017-02-06 19:06
it is in debug : 

{
  "persistent": {},
  "transient": {
    "logger": {
      "_root": "DEBUG"
    }
  }
}

**Comment by robertchen** [comment] 2017-02-06 19:43
I uses example.sh to generate 3 nodes  certificates,  the example.sh generate node-1, node-2, node-3 names,  these probably not my hostnames, so I disable ssl_certificate_verification => false 

If I set ssl_certificate_verification => true, I saw this error in the log:

logstash-plain.log:[2017-02-06T12:59:07,350][WARN ][logstash.outputs.elasticsearch] UNEXPECTED POOL ERROR {:e=>#<Manticore::UnknownException: Host name '10.8.8.246' does not match the certificate subject provided by the peer (CN=node-1.example.com, OU=SSL, O=Test, L=Test, C=DE)>}

**Comment by robertchen** [comment] 2017-02-06 21:29
Elasticsearch.yml:

[root@ip-10-8-8-246 ec2-user]# cat /etc/elasticsearch/elasticsearch.yml
cluster.name: ELK-TUHAO
path.data: /data
node.name: usg-elk-a
network.host: 10.8.8.246
action.destructive_requires_name: true
bootstrap.memory_lock: true
discovery.zen.minimum_master_nodes: 2
logger._root: DEBUG

# set the list of hosts for unicast discovery, need set this in ansible
discovery.zen.ping.unicast.hosts: ['10.8.8.246', '10.8.8.209', '10.8.8.248']

#enable safe guard
searchguard.ssl.transport.keystore_filepath: usg-elk-a-keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
searchguard.ssl.transport.enforce_hostname_verification: false
#searchguard.ssl.transport.http.enforce_clientauth: false


searchguard.authcz.admin_dn:
  - CN=kirk, OU=client, O=client, L=Test, C=DE

#enable REST API with https:
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: usg-elk-a-keystore.jks
searchguard.ssl.http.keystore_password: changeit
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: changeit

please help, thanks.

**Comment by robertchen** [comment] 2017-02-07 16:00
Debug log attached:

[usg-elk-b-2-7.txt](https://github.com/floragunncom/search-guard/files/758211/usg-elk-b-2-7.txt)
[usg-elk-a-2-7.txt](https://github.com/floragunncom/search-guard/files/758213/usg-elk-a-2-7.txt)
[usg-elk-c-2-7.txt](https://github.com/floragunncom/search-guard/files/758212/usg-elk-c-2-7.txt)

**Comment by robertchen** [comment] 2017-02-07 16:17
Seems from logstash, even I set any indices, it still try to match only logstash-*

  indices:
    '*':
      '*':
        - ALL

I tried to setup index name as index => "mycompany-%{type}-%{+YYYY.MM.dd}"  
probably this is the issue?

**Comment by floragunncom** [comment] 2017-02-07 18:02
It seems that you have not updated/uploaded your sg_roles.yml via sgadmin. Every time you make changes in sg_roles.yml (and other sg_*.yml files) you need to run sgadmin to push them

**Comment by robertchen** [comment] 2017-02-07 18:16
thanks, does it need run on all nodes or just one?

**Comment by floragunncom** [comment] 2017-02-07 18:50
one

**Comment by floragunncom** [comment] 2017-02-14 19:40
Does it now work for you? If yes pls. close this issue

**Comment by robertchen** [comment] 2017-02-14 21:48
Yes, thanks.

**Closed** 2017-02-14 21:49 UTC
