### ISSUE TITLE
Search Guard not initialized Elasticsearch 5.5.0 - no permissions for indices:admin/exists

### ISSUE THREAD

**Issue by jens-ab** [floragunncom/search-guard#366] opened 2017-07-13 12:01 UTC
Hello,

i updated Elasticsearch from 5.2 to 5.5.0.
After installing searchguard i become the following error, when i want to initialize searchguard.

<pre>
Clusterstate: GREEN
Number of nodes: 1
Number of data nodes: 1
ERR: An unexpected ElasticsearchSecurityException occured: no permissions for indices:admin/exists
Trace:
ElasticsearchSecurityException[no permissions for indices:admin/exists]
        at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:147)
        at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:168)
        at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:142)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:64)
        at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:54)
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceivedDecorate(SearchGuardSSLRequestHandler.java:177)
        at com.floragunn.searchguard.transport.SearchGuardRequestHandler.messageReceivedDecorate(SearchGuardRequestHandler.java:191)
        at com.floragunn.searchguard.ssl.transport.SearchGuardSSLRequestHandler.messageReceived(SearchGuardSSLRequestHandler.java:139)
        at com.floragunn.searchguard.SearchGuardPlugin$2$1.messageReceived(SearchGuardPlugin.java:336)
        at org.elasticsearch.transport.RequestHandlerRegistry.processMessageReceived(RequestHandlerRegistry.java:69)
        at org.elasticsearch.transport.TcpTransport$RequestHandler.doRun(TcpTransport.java:1544)
        at org.elasticsearch.common.util.concurrent.AbstractRunnable.run(AbstractRunnable.java:37)
        at org.elasticsearch.common.util.concurrent.EsExecutors$1.execute(EsExecutors.java:110)
        at org.elasticsearch.transport.TcpTransport.handleRequest(TcpTransport.java:1501)
        at org.elasticsearch.transport.TcpTransport.messageReceived(TcpTransport.java:1385)
        at org.elasticsearch.transport.netty4.Netty4MessageChannelHandler.channelRead(Netty4MessageChannelHandler.java:74)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:310)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:297)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:413)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1267)
        at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1078)
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489)
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858)
        at java.lang.Thread.run(Thread.java:748)
</pre>

Does anyone know this error?

**Comment by floragunncom** [comment] 2017-07-13 12:02
maybe the same problem like https://groups.google.com/forum/#!msg/search-guard/cbSUX9q4Bp0/46tuDCvtBgAJ

**Comment by hex2a** [comment] 2017-07-13 12:08
I'm experiencing the same problem. (`5.4.0-12` -> `5.5.0-14`)

**Comment by jens-ab** [comment] 2017-07-13 12:17
Yes, it seems to be the same problem.
But I can not get the workaround to run.

**Comment by floragunncom** [comment] 2017-07-13 12:18
check that your certificate is a client admin cert (not a node certificate)

**Comment by hex2a** [comment] 2017-07-13 12:19
It is a node certificate, but this worked before.

**Comment by jens-ab** [comment] 2017-07-13 13:30
i generated new certificate with search-guard-ssl-ves-5.5.0-22/example-pki-scripts/example.sh

now i have the following error:
[Error.txt](https://github.com/floragunncom/search-guard/files/1145300/Error.txt)

i can connect to elasticsearch and the login is working.
Only Kibana is not running.

Any idea what the error is? I will check the doku for now, maybe i can find there anything.

**Comment by hex2a** [comment] 2017-07-13 13:32
@jens-ab seems like the (root) CA Certificate is not trusted, did you update the truststore?

**Comment by jens-ab** [comment] 2017-07-13 13:39
i updated everything. Maybe some settings in the scripts were wrong. i will check it again.

**Comment by jens-ab** [comment] 2017-07-13 14:42
Are there some changes in searchguard, where the CA Certificate and truststore from search-guard-ssl-ves-5.5.0-22/example-pki-scripts/example.sh not allowed anymore?

I generate the root CA Certificate and use the generated files from gen_client_node_cert.sh

I have done the same changes like before.
Elasticsearch is running and login is working. But Kibana can not conect with message 
[security_exception] no permissions for indices:data/read/mget

To check, i have given the kibana user admin rights.

Also there is the exception from sgadmin.sh. The diagnose gives the following file:
[sgadmin_diag_trace_2017-Jul-13_16-30-32.txt](https://github.com/floragunncom/search-guard/files/1145545/sgadmin_diag_trace_2017-Jul-13_16-30-32.txt)

I don't understand what happend between com.floragunn:search-guard-5:5.2.1-11 and com.floragunn:search-guard-5:5.5.0-14

Are there any hints I can follow here?

**Comment by floragunncom** [comment] 2017-07-13 19:07
There are no changes where CA Certificate and truststore example.sh not allowed anymore. I guess you missed something to update (you need to update all nodes and sgadmin as well).

Pls post your elasticsearch.yml and your sgadmin command. The Kibana issue we will fix later if anything else is running.

@hex2a Seems we missed to document this change but node certificates where never really supported for sgadmin and where never supposed to be working like that.

**Comment by floragunncom** [comment] 2017-07-13 19:08
@hex2a is it now working for you again?

**Comment by hex2a** [comment] 2017-07-14 10:46
@floragunncom the sgconfig files are managed through a configuration management tool on the nodes, and then pushed into elasticsearch using the respective node certificate. Is there any possibility to keep this behaviour?

**Comment by jens-ab** [comment] 2017-07-17 10:16
Hello,

i was on vacation and could not answer earlier.

the sgadmin command is:
/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh  -cd /srv/elasticsearch/config/  -ks /srv/elasticsearch/config/vm_dev-keystore.jks  -kspass password  -ts /srv/elasticsearch/config/truststore.jks  -tspass password  -nhnv  -icl --diagnose


The entry in elasticsearch.yml is:
`#############################################################################################
#                                     SEARCH GUARD SSL                                      #
#############################################################################################

searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: vm_dev-keystore.jks
searchguard.ssl.transport.keystore_alias: vm_dev
searchguard.ssl.transport.keystore_password: password

searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_alias: root-ca-chain
searchguard.ssl.transport.truststore_password: password

searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true

#############################################################################################
#                                     SEARCH GUARD                                          #
#############################################################################################

searchguard.authcz.admin_dn:
  - "CN=vm_dev, OU=client, O=client, L=test, C=de"
  - "CN=192.168.1.120, OU=SSL, O=Test, L=Test, C=DE"
`

I'm using this setting since elasticsearch 2.4.

**Comment by jens-ab** [comment] 2017-07-17 14:17
Hello,

i have solved my problem. Apparently one must now use the node name in elasticsearch.yml.

Kibana is running to and sgadmin doesn't produce any errors.

**Comment by pworoniecki** [comment] 2017-07-17 14:36
@jens-ab could you write where exactly did you use the node name? in CN of searchguard.authcz.admin_dn or somewhere else?
I run into the same issue as you did after upgrading from 5.4.2 to 5.5.0

**Comment by jens-ab** [comment] 2017-07-17 15:24
yes, i will try to write down all changes:

elasticsearch.yml:


#############################################################################################
#                                     SEARCH GUARD SSL                                      #
#############################################################################################

searchguard.ssl.transport.keystore_type: JKS
searchguard.ssl.transport.keystore_filepath: NODENAME-keystore.jks
searchguard.ssl.transport.keystore_alias: NODENAME
searchguard.ssl.transport.keystore_password: changeit

searchguard.ssl.transport.truststore_type: JKS
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_alias: root-ca-chain
searchguard.ssl.transport.truststore_password: changeit

searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.resolve_hostname: false
searchguard.ssl.transport.enable_openssl_if_available: true
searchguard.ssl.http.enable_openssl_if_available: true

#############################################################################################
#                                     SEARCH GUARD                                          #
#############################################################################################

searchguard.authcz.admin_dn:
  - "CN=NODENAME, OU=client, O=client, L=test, C=de"
  - "CN=LOCALIP, OU=SSL, O=Test, L=Test, C=DE"


search-guard-ssl-ves-5.5.0-22/example-pki-scripts/example.sh:
#!/bin/bash
set -e
./clean.sh
./gen_root_ca.sh capass changeit
./gen_client_node_cert.sh NODENAME changeit capass
rm -f ./*tmp*

sgadmin command is:
/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh  -cd /srv/elasticsearch/config/  -ks /srv/elasticsearch/config/NODENAME-keystore.jks  -kspass changeit  -ts /srv/elasticsearch/config/truststore.jks  -tspass changeit  -nhnv  -icl --diagnose

This ist working for me with 1 Node. 
Elasticsearch version 5.5

if there is any question just ask

**Comment by pworoniecki** [comment] 2017-07-17 16:39
Thank you for sharing your configuration. Unfortunately it doesn't work for me in my 3 nodes setup. I created client cert with CN=NODENAME where NODENAME was name of the node where I executed sgadmin. 
I get this error:

>  	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:489) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:428) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:265) ~[netty-codec-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:340) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:348) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:134) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:644) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:544) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:498) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:458) [netty-transport-4.1.11.Final.jar:4.1.11.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:858) [netty-common-4.1.11.Final.jar:4.1.11.Final]
	at java.lang.Thread.run(Thread.java:748) [?:1.8.0_131]
Caused by: sun.security.validator.ValidatorException: PKIX path validation failed: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:352) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260) ~[?:?]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:223) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:645) ~[?:?]
	... 25 more
Caused by: java.security.cert.CertPathValidatorException: Path does not chain with any of the trust anchors
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:153) ~[?:?]
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79) ~[?:?]
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:292) ~[?:1.8.0_131]
	at sun.security.validator.PKIXValidator.doValidate(PKIXValidator.java:347) ~[?:?]
	at sun.security.validator.PKIXValidator.engineValidate(PKIXValidator.java:260) ~[?:?]
	at sun.security.validator.Validator.validate(Validator.java:260) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.validate(X509TrustManagerImpl.java:324) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkTrusted(X509TrustManagerImpl.java:281) ~[?:?]
	at sun.security.ssl.X509TrustManagerImpl.checkServerTrusted(X509TrustManagerImpl.java:136) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslClientContext$ExtendedTrustManagerVerifyCallback.verify(ReferenceCountedOpenSslClientContext.java:223) ~[?:?]
	at io.netty.handler.ssl.ReferenceCountedOpenSslContext$AbstractCertificateVerifier.verify(ReferenceCountedOpenSslContext.java:645) ~[?:?]
	... 25 more 

So it seems I have the same problem as you had earlier but there must be something another. My setup worked in all earlier versions, including 5.4.2. It stopped working in 5.5.

**Comment by jens-ab** [comment] 2017-07-17 16:54
Sorry, there i can't help you. I haven't use searchgurd with more than one node.

**Comment by pworoniecki** [comment] 2017-07-17 17:04
Sure, thanks anyway. Maybe your config will help other people.
As I have the same problem as you had earlier, I would like to get help from somebody another here as well - as further people may have the same problem when trying to setup more than 1 node.

I have 3 nodes and for each of them I have config like that:

**elasticsearch.yml** content:
`   path:
      logs: /tmp
      conf: /usr/share/elasticsearch/config
      repo: /usr/share/elasticsearch/backups
    network:
      host: 0.0.0.0
    cluster:
      name: sg-cluster
    node:
      name: ${NODE_NAME}
      master: ${IS_NODE_MASTER}
      data: ${IS_NODE_DATA}
      attr.tag: ${NODE_TAG}
    discovery:
      zen:
        ping.unicast.hosts: ${DISCOVERY_SERVICE}
        minimum_master_nodes: ${NUMBER_OF_MASTER_NODES}
    http.max_header_size: 32kb
    searchguard:
      ssl:
        transport:
          keystore_filepath: node-keystore.jks
          keystore_password: ${KEYSTORE_PASSWORD}
          truststore_filepath: truststore.jks
          truststore_password: ${TRUSTSTORE_PASSWORD}
          enforce_hostname_verification: false
        http:
          enabled: true
          keystore_filepath: node-keystore.jks
          keystore_password: ${KEYSTORE_PASSWORD}
          truststore_filepath: truststore.jks
          truststore_password: ${TRUSTSTORE_PASSWORD}
    searchguard.authcz.admin_dn:
      - CN=${NODE_NAME},OU=Test,O=Test,L=Test,ST=test,C=DE`

All env variables are correctly filled with proper names (I also tried to hardcode all of them to be sure).
I generated 3 node certs - one per elastic node + 1 client cert with proper data: CN=${NODE_NAME},OU=Test,O=Test,L=Test,ST=test,C=DE

I used certs generated by scripts from example-pki-scripts.

**Comment by floragunncom** [comment] 2017-07-17 20:40
The solution is quite easy: Do not use a node certificate for sgadmin and searchguard.authcz.admin_dn. Instead use a client certificate (like spock or kirk if you use the example pki scripts). Even if you get it working somehow we will not guarantee that this will work in later versions too. It is not (it it never was) supported to use a node certificate with sgadmin.

Btw: We understand that all the different certificates are complex to handle and therefore sgadmin and all the other certificate stuff will become way easier with ES 6/SG 6. But there will be no backport to ES 5/SG 5 for this.

**Comment by floragunncom** [comment] 2017-07-17 20:43
Use the `spock-keystore.jks` with sgadmin and configure
<pre>
searchguard.authcz.admin_dn:
  - "CN=spock, OU=client, O=client, L=Test, C=DE"
</pre>
on all nodes. That should work without any hassle.

**Comment by pworoniecki** [comment] 2017-07-18 05:47
I was using client certificate (when I used node cert previously I got _no permissions for indices:admin/exists_ error).
But I started whole procedure from scratch and it finally worked. I generated my own client cert with CN not containing node name and it works - just as it works for spock-keystore.jks. So it seems that CN may be anything.
I found also the reason of my previous failure (see: https://github.com/floragunncom/search-guard/issues/366#issuecomment-315808991): I forgot to replace truststore.jks file on one of nodes but replaced on two others. Maybe it helps someone too.

Thank you @floragunncom for your help.

**Comment by floragunncom** [comment] 2017-07-18 06:08
The CN for a client certificate maybe anything (and normally is above all not related to a hostname or nodename or similar) because the CN in a client certificate is like the "username" whereas the private key part of certificate is the "password". To make a client certificate a sgadmin/sg admin certificate you have to list the CN of it in `searchguard.authcz.admin_dn:`. Client certificates who are not admin certificates are also supposed to be used with TransportClienst to connect programmatically to elasticsearch using the transport protocol (port 9300, not related to REST/HTTP).

Node certificates instead should contain the hostname in the CN attribute to make hostname verification work. But they are supposed to identify nodes to each other, that is why they contain this mystery OID so that we can distinguish them from a client certificate and must not be used as such.

**Comment by floragunncom** [comment] 2017-08-08 15:52
in SG v15 we added a explanatory error message to sgadmin.
Will close this issue.

**Closed by floragunncom** 2017-08-08 15:52 UTC
