### ISSUE TITLE
searchguard.enterprise_modules_enabled: false

### ISSUE THREAD

**Issue by ankit22550** [floragunncom/search-guard#656] opened 2019-03-19 15:15 UTC
Hello Team, 

i just install search-guard-5-5.6.5-18 pulgin on elasticsearch 5.6 version but after setting the elasticsearch.yml if i used **searchguard.enterprise_modules_enabled: false** setting on yml file its show me below error.
**org.elasticsearch.bootstrap.StartupException: java.lang.IllegalArgumentException: unknown setting [searchguard.enterprise_modules_enabled] please check that any required plugins are installed, or check the breaking changes documentation for removed settings**

**Comment by floragunncom** [comment] 2019-03-19 15:18
searchguard.enterprise_modules_enabled is only available since ES 6.0.0. Please refer to 5.x docs: https://docs.search-guard.com/v5/index

**Comment by floragunncom** [comment] 2019-03-19 15:18
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Closed by floragunncom** 2019-03-19 15:18 UTC
