### ISSUE TITLE
GUI support

### ISSUE THREAD

**Issue by superkeil** [floragunncom/search-guard#63] opened 2015-12-10 10:47 UTC
Hello,
it would be great to have a GUI for managing permissions.
I have a very little need since i like to use ES JS Client :
Create a user, assign him read-only permission over a specific index.
Right now, i am confused how much efforts it take for just doing that task.

**Comment by floragunncom** [comment] 2016-05-01 12:58
duplicate of #106

**Closed by floragunncom** 2016-05-01 12:58 UTC
