### ISSUE TITLE
Session timeout leads to exception / dead links

### ISSUE THREAD

**Issue by unimountain** [floragunncom/search-guard#422] opened 2017-12-05 15:45 UTC
## System info
* Search Guard and Elasticsearch version
  * Search Guard 5.3.3
  * Elasticsearch 5.3.3
  * _Search Guard 6.0.0 (see update section below)_
* JVM version and operating system version
  * openjdk version "1.8.0_131"
* Number of nodes in your cluster
  * 1
* Description of the bug
  * If a session expires (searchguard.session.ttl or searchguard.cookie.ttl reached) an error message is shown.
![screenshot-session-expired-error](https://user-images.githubusercontent.com/34271760/33615425-66120b52-d9da-11e7-8835-1d0a318db1cb.png)

## Steps to reproduce
Set a low **searchguard.session.ttl** or **searchguard.cookie.ttl** setting to reproduce quickly.
If the ttl is reached click in Kibana on "Discover" or "Visualize" and you see the error message (see attachment). This behaviour is confusing for our users. 
The expectation would be a redirect to the login page with an appropriate expiration message.

**Update:**
I just tested this with Elasticsearch 6.0 and Search Guard 6.0.0-17.beta1 and there isn't even an error message at all (only JS errors hidden in the developer console). The main navigation just doesn't work anymore until you reload the whole page.
Here I would also expect Search Guard to redirect to the login page if the session expires and you try to use the navigation.

**Comment by floragunncom** [comment] 2017-12-28 12:35
We also have this which seems to be more or less the same issue: "I noticed that when I do not use kibana for a while but the tab is still open, then if I try to make a filter or interact with the dashboard you do don't get anything back. This happens because the session expired and this is great but the problem is that there is no feedback from the UI and you are redirected to the login page only if you reload the whole page."
https://groups.google.com/forum/#!msg/search-guard/xhPjjFWnwtE/pu3p4F3eBAAJ

**Comment by floragunncom** [comment] 2018-02-11 19:41
Issue is fixed and will be released with the next version of the Kibana Plugin. We leave the issue open until release is done.

**Comment by jochenkressin** [comment] 2018-04-03 21:35
Fixed with Search Guard v22 and Kibana Plugin v11: https://docs.search-guard.com/latest/changelog-6-x-22

**Closed by jochenkressin** 2018-04-03 21:35 UTC
Labels: SG5, SG6, bug, kibana
