### ISSUE TITLE
`sg_own_index` rolemapping is required and not optional for multitenancy

### ISSUE THREAD

**Issue by anandsinghkunwar** [floragunncom/search-guard#579] opened 2018-11-16 07:35 UTC
### Description of the bug
`sg_own_index` role and role_mapping that gives a user to all permissions to an index with their own username seems to be a required role/role_mapping for Search Guard multi-tenancy to work. When removing that role mapping  users with RW access to a tenant aren't able to modify dashboards. It throws the following error:
```
Visualization Editor: no permissions for [indices:data/write/bulk] and User [name=random_username, roles=[role1, role2, role3], requestedTenant=test_tenant]: [security_exception] no permissions for [indices:data/write/bulk] and User [name=random_username, roles=[role1, role2, role3], requestedTenant=test_tenant], requestedTenant=test_tenant]
```
In case this is a required role / role_mapping, it should be documented as I couldn't find it anywhere. 
### Environment
* Search Guard Version: `6.3.1-23.1`
* Elasticsearch Version: `6.3.1`
* Java Version: `1.8.0_172`
* Operating System: Centos 7 
* Number of nodes in your cluster: 4 Data Node, 3 Master Nodes

**Comment by jochenkressin** [comment] 2018-11-16 19:19
Cannot reproduce. The sg_own_index role is not required to create visualizations or use multi tenancy. 

I guess the Search Guard roles you assigned your user to lack bulk permissions on cluster level. The sg_own_index role contains these permissions.

A Kibana user needs to have:

1. the permissions as defined in the sg_kibana_user demo role
2. permissions to the index / indices he/she should be able to see

Please compare your SG roles for your user with the sg_kibana_user role.

**Comment by anandsinghkunwar** [comment] 2018-11-19 13:40
It seems `CLUSTER_COMPOSITE_OPS` is a cluster-wide permission that is required. It seems to work without the access to 
```
  cluster:
    - INDICES_MONITOR
  indices:
    '?kibana':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '?kibana-6':
      '*':
        - MANAGE
        - INDEX
        - READ
        - DELETE
    '*':
      '*':
        - indices:data/read/field_caps*
```
Are these really required, if yes, where?

**Comment by floragunncom** [comment] 2018-12-06 13:34
Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Closed by floragunncom** 2018-12-06 13:34 UTC
