### ISSUE TITLE
ElasticSearch process extreme load when SG has lots of roles or role mappings

### ISSUE THREAD

**Issue by farzadghanei** [floragunncom/search-guard#635] opened 2019-02-11 15:51 UTC
Hi

We're experiencing very high CPU loads on ElasticSearch nodes with SearchGuard indices. We have not pin pointed anything in particular, nothing shows up in logs, no code/settings/usage behavior was changed on the ES cluster. The only change was that we increased the number of roles/roles mapping. When the number of roles/role mappings reached 140+, ElasticSearch process started consuming lots of resources. It was not a steady high load though, much higher than usual with sudden spikes to states where the nodes were just not responsive anymore. We removed some roles/roles mapping and the load went down to what it was before.

Since our setup binds role mappings and roles, we're still not sure which one is causing this.

### System info:
 * Debian GNU/Linux 8.10 (jessie)
 * Java: 
    * OpenJDK Runtime Environment (build 1.8.0_171-8u171-b11-1~bpo8+1-b11)
    * OpenJDK 64-Bit Server VM (build 25.171-b11, mixed mode)
 * ES and Kibana: `6.2.3`
 * Kibana SG plugin: `6.2.3-14`
 * SG modules:
    * Audit Logging (enterprise, `6.2.3.32-0`)
    * Document and Field-level security (enterprise, `6.2.3.32-0`)
    * HTTP Basic Authenticator (`6.2.3.23-0`)
    * Internal users authentication (`6.2.3.23-0`)
    * Kibana Multitenancy (enterprise, `6.2.3.32-0`)
    * REST Management API (enterprise, `6.2.3.32-0`)

solutions/hints are much appreciated.

**Comment by floragunncom** [comment] 2019-02-11 18:55
@farzadghanei Can you provide the sg_*.yml config files for which you see the high load? You can also mail us the files (PGP encrypted if you like), see https://search-guard.com/security/

**Comment by farzadghanei** [comment] 2019-02-13 11:17
@floragunncom I sent you the PGP encrypted email.

**Comment by floragunncom** [comment] 2019-02-13 14:52
We think we have identified the root cause and we are [working on a fix](https://github.com/floragunncom/search-guard/commit/65b427c3094a7c1195fe9497633f32b8b5a51950). Like you have assumed the problem occurs when there are many role mappings because of the code loops over this very inefficiently. Until the fix is deployed you can workaround with everything that keeps the count of entries in the sg_roles_mapping.yml at a minimum. For example, you can check if you can assign the sg roles directly to the internal users, setting https://docs.search-guard.com/latest/role-mapping-modes#expert-role-mapping-modes to BOTH and the do something like:

```
myuser1:
  roles:
  - "sg_role1"
  hash: "..."
```

whereas then myuser1 would have sg_role1 (from sg_roles.yml) assigned directly without any need for an entry in sg_roles_mapping.yml

If you like, I can send you a snapshot version so you can check if the problem is fixed.

**Comment by JeroenvHeugten** [comment] 2019-02-25 16:32
Could you please send us a snapshot for v6.2.3, because we basically cannot use some of our tools right now. I think you already have Farzad's e-mail address. About the workaround:  We are not using the yml files, only the REST API.

**Comment by floragunncom** [comment] 2019-02-26 07:41
@JeroenvHeugten Will provide something within the next two days

**Comment by floragunncom** [comment] 2019-02-27 05:08
Pls try https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-6/6.2.3-23.2-SNAPSHOT/search-guard-6-6.2.3-23.2-20190227.050454-2.zip

**Comment by JeroenvHeugten** [comment] 2019-03-05 11:55
@floragunncom I installed the provided snapshot. 

However, I did not (yet) re-add the previously removed roles & rolemappings because I noticed timeouts when viewing a role in Kibana. As an example: When I open the URL `/app/searchguard-configuration#/internalusers?_g=()` in Kibana, which loads in a couple seconds and shows "2461 entries found. (fine). However, when I try to view a single role `/app/searchguard-configuration#/roles/edit/somerole_name_here?_g=()` I get a gateway timeout after 60 seconds. The page itself (default the Index Permissions tab) does load, but something keeps loading in the back.

**Comment by floragunncom** [comment] 2019-03-05 19:31
Will investigate ...

**Comment by floragunncom** [comment] 2019-03-06 22:08
We have found the root cause and currently preparing another pre-release ...

**Comment by floragunncom** [comment] 2019-03-12 14:05
@farzadghanei @JeroenvHeugten We will very likely not backport the fixes for ES 6.3 and before. Are you able to upgrade to >= 6.4? If not please contact us via email to discuss options.

**Comment by farzadghanei** [comment] 2019-03-12 14:51
@floragunncom we'll update our ES to to 6.4+, so we won't need a backport for this release. Is there an ETA for the next release that would contain this fix?

**Comment by floragunncom** [comment] 2019-03-12 21:33
Here is another snapshot based on ES 6.5.1 https://oss.sonatype.org/content/repositories/snapshots/com/floragunn/search-guard-6/6.x-HEAD-SNAPSHOT/search-guard-6-6.x-HEAD-20190312.191221-3031.zip

If this working for you we will release this week v24.2 which should fix all issues mentioned above.

**Comment by farzadghanei** [comment] 2019-03-13 15:06
Thanks. Just to double confirm, the next production release would contain both fixes (ES high CPU usage, and the Kibana timeouts), right? We'll wait for the next production release.

**Comment by floragunncom** [comment] 2019-03-13 16:07
Yes, the next production release will contain both (like the 6.5.1 snapshot). I'd like to ask you if you are able to test the 6.5.1 snapshot and confirm that both are resolved.

**Comment by farzadghanei** [comment] 2019-03-14 08:52
We have plans to update our production stack end of March. Since we observed this behavior only on production stack, I'm not sure if our dev stack tests can confirm the effects of this snapshot. We'll wait for the SG v24.2 release, and update our ES stack and SG together and will update here of what we found.

**Comment by floragunncom** [comment] 2019-03-20 00:30
Fixed with v24.2 released today.

**Closed by floragunncom** 2019-03-20 00:30 UTC
Labels: wait for user feedback
