### ISSUE TITLE
Uncaught TypeError: ace.require is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=16573:22)

### ISSUE THREAD

**Issue by brano-tichy** [floragunncom/search-guard#452] opened 2018-02-20 17:55 UTC
* ES, Kibana v 6.2.1
* SG v 6 6.2.1-21.0
* SG Kibana plugin 6.2.1-10

* OS: Windows 7 Professional 64bit SP1
* java version "9"
   Java(TM) SE Runtime Environment (build 9+181)
   Java HotSpot(TM) 64-Bit Server VM (build 9+181, mixed mode)
* test env on my desktop, so just one node ES + Kibana
   clean install, sg plugins, demo certificates, es login successfull, after login into kibana an error occurs:

```
Uncaught TypeError: ace.require is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=16573:22)
Version: 6.2.1
Build: 16573
Error: Uncaught TypeError: ace.require is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=16573:22)
    at window.onerror (http://localhost:5601/bundles/commons.bundle.js?v=16573:1:505915)
```

**Comment by floragunncom** [comment] 2018-02-20 18:36
Which browser are you using?

**Comment by floragunncom** [comment] 2018-02-20 18:40
Plus, does this also happen when you remove the Search Guard plugin? In the error you sent I do not see any SG related information. Thx!

**Comment by brano-tichy** [comment] 2018-02-21 10:40
* ok, i deleted kibana, uninstalled SG plugin from ES, used original configs -- everything worked
* then installed SG on ES. worked.
* plain Kibana _without_ sg plugin worked too, with edited config.
* then i installed plugin for kibana:
   ```
   kibana-plugin.bat install file:///<full_path>\search-guard-kibana-plugin-6.2.1-10.zip
   Attempting to transfer from file:///<full_path>\search-guard-kibana-plugin-6.2.1-10.zip
   Transferring 2926457 bytes....................
   Transfer complete
   Retrieving metadata from plugin archive
   Extracting plugin archive
   Extraction complete
   Optimizing and caching browser bundles...
   Plugin installation complete
   ```

now kibana starts with SG login dialog, and after logging immediately throws the fatal error.
re different browser:
* Chrome:
   ```
   Uncaught TypeError: ace.require is not a function (http://localhost:5601/bundles/kibana.bundle.js?v=16573:22)
   ```
* IE:
   ```
   Object doesn't support property or method 'require' (http://localhost:5601/bundles/kibana.bundle.js?v=16573:22)
   ```

and now i see the offending library isn't part of SG, but of kibana itself.
however something bad happened in the "optimizing" step of plugin installation.

these files in ```optimize/bundles/``` have different checksum:
```
commons.bundle.js
commons.style.css
kibana.bundle.js
kibana.entry.js
stateSessionStorageRedirect.bundle.js
stateSessionStorageRedirect.entry.js
status_page.bundle.js
status_page.entry.js
timelion.bundle.js
timelion.entry.js
vendors.bundle.js
```
+ there are some new ```searchguard-{configuration,login,multitenancy}.*.*``` files

* _removing_ kibana plugin triggered optimize and cache step upon starting, the new kibana.bundle.js is yet different and the error persisted

**Comment by brano-tichy** [comment] 2018-02-26 08:15
FYI i openned an issue with kibana [https://github.com/elastic/kibana/issues/16866](url), they shrugged it off

> SearchGuard plugins are not supported. Contact SearchGuard for support

**Comment by floragunncom** [comment] 2018-02-26 09:50
Cannot reproduce and have not heard of this issue before, but we're investigating. Issue is tracked here: https://github.com/floragunncom/search-guard-kibana-plugin/issues/80

**Comment by jochenkressin** [comment] 2018-02-27 08:59
Closing issue here, tracked in Kibana Plugin Issue Tracker floragunncom/search-guard-kibana-plugin#80.

**Closed by jochenkressin** 2018-02-27 08:59 UTC

**Comment by callahan22** [comment] 2018-05-08 19:49
Already commented in jochenkressin's Issue Tracker link but for the sake anyone that doesn't click that far, the solution is to install the search-guard-kibana-plugin through Powershell not the cmd.
Once it's done this way, start up Kibana.bat from within the same Powershell window and test.
Once you've confirmed that works, you can terminate the process in PS and go back to running it as a service or however you used to start it up.
