### ISSUE TITLE
After search-guard install, I can't use _plugin url

### ISSUE THREAD

**Issue by klinux** [floragunncom/search-guard#81] opened 2016-01-13 18:01 UTC
After search-guard installed, I can't use _plugin url, for example, http://server:9200/_plugin/HQ, or any other plugin.

I get this error:
{"error":"ClassCastException[com.floragunn.searchguard.http.netty.SessionAwareNettyHttpChannel cannot be cast to org.elasticsearch.http.HttpChannel]","status":500}
Someone knows how do I fix it?

Edit: ElasticSearch 1.7.4, RedHat Linux 6.5, JVM 1.7.60

Thanks

**Comment by klinux** [comment] 2016-01-18 16:48
I've created this workaround in AbstractACRestFilter.java, for the plugin work again. Is obviously a ugly thing, but now _plugin uri works again. I miss some thing in the configuration?

String _plugin = "_plugin";
if (request.uri().contains(_plugin)) {
    log.debug("This is a _plugin request, will allow");
    filterChain.continueProcessing(request, origRestChannel);
    return;
}

**Comment by ChinaChaos** [comment] 2016-02-02 05:03
why i not foud the problem? es1.5.1 , search-guard5.0

**Comment by ChinaChaos** [comment] 2016-02-02 05:03
why i am not foud the problem? es1.5.1 , search-guard5.0

**Comment by klinux** [comment] 2016-02-02 11:54
Well, I can't say, but my deployment is different than yours. ES 1.7.4  and new version of search-guard.

Thank you

**Comment by floragunncom** [comment] 2016-05-01 12:53
duplicate of #75

**Comment by floragunncom** [comment] 2016-05-01 12:53
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Closed by floragunncom** 2016-05-01 12:53 UTC
Labels: site plugins
