### ISSUE TITLE
Can not set searchguard.ssl.transport.enabled to false

### ISSUE THREAD

**Issue by qli-aa** [floragunncom/search-guard#172] opened 2016-07-14 08:11 UTC
ES: 2.3.3
JVM: 1.8.0_91
Num of Nodes: 3
* Description of the bug

[2016-07-14 08:07:10,650][INFO ][node                     ] [ec2-xxx] version[2.3.3], pid[52917], build[218bdf1/2016-05-17T15:40:04Z]
[2016-07-14 08:07:10,650][INFO ][node                     ] [ec2-xxx] initializing ...
[2016-07-14 08:07:11,145][ERROR][bootstrap                ] Exception
ElasticsearchException[Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]]; nested: InvocationTargetException; nested: IllegalStateException[searchguard.ssl.transport.enabled must be set to 'true'];
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:483)
	at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:432)
	at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
	at org.elasticsearch.node.Node.<init>(Node.java:158)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:472)
	... 8 more
Caused by: java.lang.IllegalStateException: searchguard.ssl.transport.enabled must be set to 'true'
	at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:58)
	... 13 more

**Comment by qli-aa** [comment] 2016-07-14 08:12
Just want disable both transport ssl and http ssl, only enable authentication and authorization of search-guard

**Comment by floragunncom** [comment] 2016-07-14 08:18
Duplicate of #165

**Closed by floragunncom** 2016-07-14 08:18 UTC
