### ISSUE TITLE
Weird exception with unresolvable unicast hosts

### ISSUE THREAD

**Issue by fabiocorneti** [floragunncom/search-guard#254] opened 2016-12-13 08:56 UTC
Elasticsearch Version: 2.4.1
SearchGuard SSL version: 2.4.1.16
SearchGuard 2 Version: 2.4.1.8

If `discovery.zen.ping.unicast.hosts` is set to a hostname which can't be resolved, e.g.:

```
discovery.zen.ping.unicast.hosts: ["nope"]
```

Elasticsearch terminates with the following exception:

```
[2016-12-13 01:41:53,919][WARN ][com.floragunn.searchguard.transport.SearchGuardTransportService] [Order] registered two transport handlers for action cluster:admin/searchguard/config/update, handlers: com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@7a83ccd2, com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@76ff68c5
[2016-12-13 01:41:53,919][WARN ][com.floragunn.searchguard.transport.SearchGuardTransportService] [Order] registered two transport handlers for action cluster:admin/searchguard/config/update[n], handlers: com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@44aa2e13, com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@6418e39e
[2016-12-13 01:41:53,920][WARN ][com.floragunn.searchguard.transport.SearchGuardTransportService] [Order] registered two transport handlers for action cluster:admin/searchguard/config/update, handlers: com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@599a9cb2, com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@7a83ccd2
[2016-12-13 01:41:53,920][WARN ][com.floragunn.searchguard.transport.SearchGuardTransportService] [Order] registered two transport handlers for action cluster:admin/searchguard/config/update[n], handlers: com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@3a1b36a1, com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor@44aa2e13
Exception in thread "main" java.lang.IllegalStateException: This is a proxy used to support circular references involving constructors. The object we're proxying is not constructed yet. Please wait until after injection has completed to use this object.
	at <<<guice>>>
	at com.sun.proxy.$Proxy13.addLifecycleListener(Unknown Source)
	at com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction.<init>(TransportConfigUpdateAction.java:87)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

If possible I think it would be better to fail with the same message as plain Elasticsearch, `Failed to resolve address for [<hostname>]`; this is useful for example in Kubernetes when unicast_hosts points to a service name that can be easily mistyped.

**Comment by floragunncom** [comment] 2016-12-13 12:09
The plain elasticsearch error has the same root cause (`<<<guice>>>`) but seems to show only the root cause.

Will try to fix this issue by doing the same, hope thats ok.


_Plain elasticsearch error_
```
[2016-12-13 13:06:12,998][WARN ][env                      ] [James Howlett] max file descriptors [10240] for elasticsearch process likely too low, consider increasing to at least [65536]
Exception in thread "main" java.lang.IllegalArgumentException: Failed to resolve address for [host1]
Likely root cause: java.net.UnknownHostException: host1: unknown error
	at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
	at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:907)
	at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1302)
	at java.net.InetAddress.getAllByName0(InetAddress.java:1255)
	at java.net.InetAddress.getAllByName(InetAddress.java:1171)
	at java.net.InetAddress.getAllByName(InetAddress.java:1105)
	at org.elasticsearch.transport.netty.NettyTransport.parse(NettyTransport.java:744)
	at org.elasticsearch.transport.netty.NettyTransport.addressesFromString(NettyTransport.java:696)
	at org.elasticsearch.transport.TransportService.addressesFromString(TransportService.java:424)
	at org.elasticsearch.discovery.zen.ping.unicast.UnicastZenPing.<init>(UnicastZenPing.java:160)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
	at <<<guice>>>
	at org.elasticsearch.node.Node.<init>(Node.java:213)
	at org.elasticsearch.node.Node.<init>(Node.java:140)
	at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
	at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:194)
	at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:286)
	at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
```

**Comment by ashish-singh-bist** [comment] 2018-02-12 07:47
I am also facing this issue. how do you fixed this issue
I install elasticsearch, and config the elastic /etc/elasticsearch/elasticsearch.yml
=============================
 cluster.name: testCluster1
 node.name: sg2
 network.host: xxx.xx.xxx.xx
 discovery.zen.ping.unicast.hosts: ["sg1", "sg2"]
 discovery.zen.minimum_master_nodes: 2
=============================
when I start service getting below error I mentioned and not started.
[ERROR][bootstrap] Guice Exception: java.lang.IllegalArgumentException: Failed to resolve address for [sg1]
Likely root cause: java.net.UnknownHostException: sg1: unknown error

**Comment by floragunncom** [comment] 2018-02-12 07:52
@ashish-singh-bist "sg1" is a host that does not exists. This issue is just about the kind of exceptional message which is displayed. Try replacing "sg1" with the ip address of your host and make sure you have a proper DNS setup. From the box where you installed elasticsearch your should be able to ping the hosts, so try if "ping sg1" is working, if not its not about Search Guard.

**Comment by ashish-singh-bist** [comment] 2018-02-12 09:51
Thanks @floragunncom for your reply, yes I white listed the IP address of sg1 and box with the port 9200.
and sg1 is properly ping from sg2
64 bytes from xxx.x.xx.xxx: icmp_seq=52 ttl=49 time=132 ms

**Comment by ashish-singh-bist** [comment] 2018-02-12 10:33
Thanks @floragunncom now connect to sg1,
I changed sg1 sg2 to ip and port, now working fine. Thanks
discovery.zen.ping.unicast.hosts: ["sg1", "sg2"]
discovery.zen.ping.unicast.hosts: ["xxx.x.xx.xxx:xxxx", "xxx.x.xx.xxx:xxxx"]

**Comment by floragunncom** [comment] 2018-04-08 16:37
original issue fixed with ES 6

**Closed by floragunncom** 2018-04-08 16:37 UTC
Labels: enhancement
