### ISSUE TITLE
SearchGuard & Kibana - allow filterring on index-patterns

### ISSUE THREAD

**Issue by litalk** [floragunncom/search-guard#89] opened 2016-02-14 10:43 UTC
I am using elasticsearch 1.7 with SG, trying to achieve that certain users of kibana won't be able to view index-patterns/dashboards/visualizations of indices they do not own. I know that if they don't have access to the index they won't be able to view the data, but I also do not want them to view/change their dashboards/etc... while still allowing them full control of their own dashboards.

For example:
If user john has access to index "jelly", but do not have access to index "bean", I do not want john to be able to view/edit any type of kibana-data of index "bean", but he can do whatever he wants with the kibana-data of index "jelly".

Couldn't find anyway of acheiving it since dls filter do not work with kibana, and even with them I couldn't see how to acieve it easily.

Does anyone know how and if it is possible?

here is my filters config:

searchguard.actionrequestfilter.names: ["kibana-server", "kibana-user", "index-user", "deny"]
searchguard.actionrequestfilter.kibana-server.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/create*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*"
]
searchguard.actionrequestfilter.kibana-user.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*",
  "indices:admin/mapping/put*",
  "indices:admin/mappings/fields/get*",
  "indices:admin/refresh*",
  "indices:admin/validate/query*",
  "indices:data/read/get*",
  "indices:data/read/mget*",
  "indices:data/read/search*",
  "indices:data/write/delete*",
  "indices:data/write/index*",
  "indices:data/write/update*",
  "indices:admin/create*"
]
searchguard.actionrequestfilter.index-user.allowed_actions: [
  "indices:admin/mappings/fields/get*",
  "indices:admin/validate/query*",
  "indices:data/read/search*",
  "indices:data/read/msearch*",
  "indices:admin/get*"
]
searchguard.actionrequestfilter.deny.allowed_actions: [
  "cluster:monitor/nodes/info*",
  "cluster:monitor/health*",
  "indices:admin/exists*"
]

ACL:

"acl": [
    {
        "__Comment__": "By default no filters are executed and no filters a by-passed. In such a case an exception is thrown and access will be denied.",
        "filters_bypass": [],
        "filters_execute": []
    },
    {
        "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
        "roles": ["admin"],
        "filters_bypass": ["*"],
        "filters_execute": []
    },
    {
        "__Comment__": "For role *kibana* executed filter *kibana-server*.",
        "users": ["kibana"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-server"]
    },
    {
        "__Comment__": "For role *user* executed filter *kibana-user*.",
        "roles": ["user"],
        "indices": [".kibana"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-user"]
    },
    {
        "__Comment__": "For role *user* executed filter *index-user*.",
        "roles": ["user"],
        "indices": ["fetcher*"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.index-user"]
    }

**Comment by litalk** [comment] 2016-02-14 10:46
BTW - if I restric access to a certain kibana type - it does not work...
I tried adding this to my ACL and kibana would not open.
 {
        "__Comment__": "For role *user* executed filter *kibana-user*.",
        "roles": ["user"],
        "indices": [".kibana:index-pattern"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.deny"]
    }

 {
        "__Comment__": "For role *user* executed filter *kibana-user*.",
        "roles": ["user"],
        "indices": [".kibana:dashboards", ".kibana:visualizations", ".kibana:search", ".kibana:config"],
        "filters_bypass": [],
        "filters_execute": ["actionrequestfilter.kibana-user"]
    }

**Comment by tzakrajs** [comment] 2016-02-23 23:13
I haven't spent any time trying to reproduce the issue, but you suggested that dlsfilters do not work with Kibana. Is this because kibana does not transparently proxy requests that modify .kibana index?

If it doesn't do that, it seems like you could use something like the following:
searchguard.dlsfilter.e: ["user_roles","index", "false"] # if field contains a user role (or not) match
This presumes that the role name is in the index name, but could possibly work.

**Comment by litalk** [comment] 2016-02-24 08:53
Thank you for the answer,
But dlsfilters just do not work with kibana (kibana would not open if they exist in the xml)

**Comment by floragunncom** [comment] 2016-05-01 11:21
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Closed by floragunncom** 2016-05-01 11:21 UTC
