### ISSUE TITLE
HTTP response may be 401/403 when authentication/authorization fails

### ISSUE THREAD

**Issue by sanori** [floragunncom/search-guard#25] opened 2015-07-01 07:04 UTC
It seems that AuthException makes the elastic search HTTP server response "500 Internal Server Error". But, would it be 401 Unauthorized (when username/password incorrect) or 403 Forbidden (when the user try to access unauthorized resource)?

**Comment by floragunncom** [comment] 2015-07-01 12:53
Duplicate of https://github.com/floragunncom/search-guard/issues/7

**Closed by floragunncom** 2015-07-01 12:53 UTC
