### ISSUE TITLE
Older Search Guard version  has with no install_demo_configuration.sh

### ISSUE THREAD

**Issue by mkeysersoze** [floragunncom/search-guard#405] opened 2017-11-03 16:56 UTC
* Search Guard and Elasticsearch version : 
`search-guard 2.4.6.14`
`search-guard-ssl 2.4.6.21`
`elasticsearch 2.4.6`
* JVM version and operating system version:
`openjdk version "1.8.0_65"`
`Red Hat Enterprise Linux Server 7.2`

* Number of nodes in your cluster : 1
* Description of the bug :

I downloaded the zip files from the Maven central repository and installed via the offline mode but when proceeding with the next step, I went to `<Elasticsearch directory>/plugins/search-guard-5/tools` I couldn't find `install_demo_configuration.sh` file.

I had to copy paste the last version of this file from your repository and executed `./install_demo_configuration.sh`  as a root user and got the following error : 

`Search Guard 6 Demo Installer
 ** Warning: Do not use on production or public reachable systems **
Install demo certificates? [y/N] y
Initialize Search Guard? [y/N] y
This script maybe require your root password for 'sudo' privileges
Search Guard plugin not installed. Quit.
`

**Comment by floragunncom** [comment] 2017-11-03 19:39
duplicate of https://github.com/floragunncom/search-guard/issues/385

**Closed by floragunncom** 2017-11-03 19:39 UTC
