### ISSUE TITLE
Permission denied when using elasticsearch curator

### ISSUE THREAD

**Issue by acidborn600** [floragunncom/search-guard#611] opened 2018-12-20 10:50 UTC
Running Searchguard-6.5.2-23.2 on Elasticsearch 6.5.2, I create role for Curator like this:
```
sg_curator2:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - DELETE
        - INDICES_MONITOR
    '*beat*':
      '*':
        - DELETE
        - INDICES_MONITOR
```
next i create new roles_mapping :
```
sg_curator2:
  readonly: true
  users:
  - curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net
```
next i run curator and get error:
```
2018-12-20 10:47:23,641 INFO      Preparing Action ID: 1, "close"
2018-12-20 10:47:23,662 INFO      Trying Action ID: 1, "close": Close indices older than 3 days (based on index name).
2018-12-20 10:47:23,665 ERROR     Failed to complete action: close.  <class 'curator.exceptions.FailedExecution'>: Failed to get indices. Error: AuthorizationException(403, u'security_exception', u'no permissions for [indices:monitor/settings/get] and User [name=curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net, roles=[], requestedTenant=null]')
```
if i add - curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net to sg_all_access in sg_roiles_mapping - all work fine.

**Comment by acidborn600** [comment] 2018-12-20 11:43
output of the /_searchguard/authinfo?pretty endpoint
```
curl -k -v --cacert /etc/curator/root-ca.pem \
> --key /etc/curator/curator.key \
> --cert /etc/curator/curator.pem \
> -XGET "https://172.22.16.71:9200/_searchguard/authinfo?pretty"
* About to connect() to 172.22.16.71 port 9200 (#0)
*   Trying 172.22.16.71...
* Connected to 172.22.16.71 (172.22.16.71) port 9200 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* NSS: client certificate from file
* 	subject: CN=curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net,OU=Ops,O="Elk, Inc.",DC=y2hfrpvi3pze3n4bfnp5ldgowh,DC=bx,DC=internal,DC=cloudapp,DC=net
* 	start date: Dec 12 15:45:08 2018 GMT
* 	expire date: Dec 09 15:45:08 2028 GMT
* 	common name: curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net
* 	issuer: CN=signing.ca.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net,OU=CA,O="Elk, Inc.",DC=y2hfrpvi3pze3n4bfnp5ldgowh,DC=bx,DC=internal,DC=cloudapp,DC=net
* SSL connection using TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
* Server certificate:
* 	subject: CN=elk-data-vm-0.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net,OU=Ops,O="Elk, Inc.",DC=y2hfrpvi3pze3n4bfnp5ldgowh,DC=bx,DC=internal,DC=cloudapp,DC=net
* 	start date: Dec 12 15:45:07 2018 GMT
* 	expire date: Dec 09 15:45:07 2028 GMT
* 	common name: elk-data-vm-0.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net
* 	issuer: CN=signing.ca.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net,OU=CA,O="Elk, Inc.",DC=y2hfrpvi3pze3n4bfnp5ldgowh,DC=bx,DC=internal,DC=cloudapp,DC=net
> GET /_searchguard/authinfo?pretty HTTP/1.1
> User-Agent: curl/7.29.0
> Host: 172.22.16.71:9200
> Accept: */*
> 
< HTTP/1.1 200 OK
< content-type: application/json; charset=UTF-8
< content-length: 747
< 
{
  "user" : "User [name=curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net, roles=[], requestedTenant=null]",
  "user_name" : "curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net",
  "user_requested_tenant" : null,
  "remote_address" : "172.22.16.5:51172",
  "backend_roles" : [ ],
  "custom_attribute_names" : [ ],
  "sg_roles" : [
    "sg_curator2",
    "sg_own_index"
  ],
  "sg_tenants" : {
    "curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net" : true
  },
  "principal" : "CN=curator.y2hfrpvi3pze3n4bfnp5ldgowh.bx.internal.cloudapp.net,OU=Ops,O=Elk\\, Inc.,DC=y2hfrpvi3pze3n4bfnp5ldgowh,DC=bx,DC=internal,DC=cloudapp,DC=net",
  "peer_certificates" : "2",
  "sso_logout_url" : null
}
* Connection #0 to host 172.22.16.71 left intact
```

**Comment by floragunncom** [comment] 2018-12-20 16:59
Seems sg_curator2 is missing permission to close the issue? Pls look into the search guard logfile and add the necessary permissions. See also https://docs.search-guard.com/latest/elasticsearch-curator-search-guard. This is not a bug, so I close this issue.

Please do not ask questions here. 
For that refer to https://groups.google.com/forum/#!forum/search-guard or, if you are a paying customer, contact our support.

Github is a place **only** for reporting bugs or feature requests.
If you report a bug please include **always** the following informations or the issue will likely be closed as invalid:

* Search Guard and Elasticsearch version
* Kibana plugin version
* JVM version and operating system version
* Number of nodes in your cluster
* Description of the bug
* sg_*.yml config files
* kibana.yml file
* elasticsearch.yml file

These informations are optional but are very valuable and
typically would lead to get bugs fixed faster:

* Steps to reproduce
* Logfiles on DEBUG level
* A failing unittest

**Closed by floragunncom** 2018-12-20 16:59 UTC
