### ISSUE TITLE
Kibana multi-tenancy Error 500 on Tenant list

### ISSUE THREAD

**Issue by faxm0dem** [floragunncom/search-guard#337] opened 2017-05-05 13:32 UTC
Hi,

When I hit the *Tenants* tab, it lists only *Private* and *Global*, and there's an error message at the top:

```
Error 500 Internal Server Error: An internal server error occurred
```

Nothing in the ES logs, but the following in kibana log (which is now syslog (!)):

```
May  5 15:25:34 node01 kibana[28394]: {"type":"error","@timestamp":"2017-05-05T13:25:34Z","tags":[],"pid":28394,"level":"error","message":"Uncaught error: \"value\" required in setHeader(\"authorization\", value)","error":{"message":"Uncaught error: \"value\" required in setHeader(\"authorization\", value)","name":"Error","stack":"Error: Uncaught error: \"value\" required in setHeader(\"authorization\", value)\n    at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:355:11)\n    at new ClientRequest (_http_client.js:85:14)\n    at Object.exports.request (http.js:31:10)\n    at Object.exports.request (https.js:199:15)\n    at HttpConnector.request (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:161:23)\n    at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:210:35)\n    at Object._.applyArgs (/usr/share/kibana/node_modules/elasticsearch/src/lib/utils.js:256:19)\n    at bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:957:21)\n    at _combinedTickCallback (internal/process/next_tick.js:73:7)\n    at process._tickDomainCallback (internal/process/next_tick.js:128:9)"},"url":{"protocol":null,"slashes":null,"auth":null,"host":null,"port":null,"hostname":null,"hash":null,"search":"","query":{},"pathname":"/searchguard/api/v1/multitenancy/info","path":"/searchguard/api/v1/multitenancy/info","href":"/searchguard/api/v1/multitenancy/info"}}
May  5 15:25:34 node01 kibana[28394]: Debug: internal, implementation, error
May  5 15:25:34 node01 kibana[28394]: Error: Uncaught error: "value" required in setHeader("authorization", value)
May  5 15:25:34 node01 kibana[28394]: at ClientRequest.OutgoingMessage.setHeader (_http_outgoing.js:355:11)
May  5 15:25:34 node01 kibana[28394]: at new ClientRequest (_http_client.js:85:14)
May  5 15:25:34 node01 kibana[28394]: at Object.exports.request (http.js:31:10)
May  5 15:25:34 node01 kibana[28394]: at Object.exports.request (https.js:199:15)
May  5 15:25:34 node01 kibana[28394]: at HttpConnector.request (/usr/share/kibana/node_modules/elasticsearch/src/lib/connectors/http.js:161:23)
May  5 15:25:34 node01 kibana[28394]: at sendReqWithConnection (/usr/share/kibana/node_modules/elasticsearch/src/lib/transport.js:210:35)
May  5 15:25:34 node01 kibana[28394]: at Object._.applyArgs (/usr/share/kibana/node_modules/elasticsearch/src/lib/utils.js:256:19)
May  5 15:25:34 node01 kibana[28394]: at bound (/usr/share/kibana/node_modules/elasticsearch/node_modules/lodash/dist/lodash.js:957:21)
May  5 15:25:34 node01 kibana[28394]: at _combinedTickCallback (internal/process/next_tick.js:73:7)
May  5 15:25:34 node01 kibana[28394]: at process._tickDomainCallback (internal/process/next_tick.js:128:9)
May  5 15:25:34 node01 kibana[28394]: {"type":"response","@timestamp":"2017-05-05T13:25:34Z","tags":[],"pid":28394,"method":"get","statusCode":500,"req":{"url":"/searchguard/api/v1/multitenancy/info","method":"get","headers":{"host":"localhost:8200","x-authenticated-user":"faxmodem","x-forwarded-server":"kibana.example.com, 127.0.0.1","x-forwarded-host":"kibana.example.com, 127.0.0.1:8000","x-forwarded-for":"134.158.231.43, 127.0.0.1","via":"1.1 kibana.example.com, 1.1 127.0.0.1:8000","cas-user":"faxmodem@example.com","referer":"https://kibana.example.com/app/searchguard-multitenancy","kbn-version":"5.3.2","dnt":"1","accept-encoding":"gzip, deflate","accept-language":"en,en-US;q=0.8,fr;q=0.5,de;q=0.3","accept":"application/json, text/plain, */*","user-agent":"Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0","x-authenticated-group":"common","connection":"Keep-Alive","sg_tenant":"__user__"},"remoteAddress":"127.0.0.1","userAgent":"127.0.0.1","referer":"https://kibana.example.com/app/searchguard-multitenancy"},"res":{"statusCode":500,"responseTime":23,"contentLength":9},"message":"GET /searchguard/api/v1/multitenancy/info 500 23ms - 9.0B"}
```

**Comment by jochenkressin** [comment] 2017-05-05 13:48
I have a guess, seems like a bug in the plugin. Are you using the plugin with SSO (like JWT or proxy auth)? I guess you have basicauth.enabled set to false, and multitenancy.enabled set to true, right?

**Comment by faxm0dem** [comment] 2017-05-05 13:56
yes exactly

**Comment by jochenkressin** [comment] 2017-05-05 21:04
I can confirm that this is actually a bug in the plugin which occurs whenever the credentials are not stored in the authorization header of the request, and either the "authinfo" or "kibanainfo" endpoint is called. Basic Auth, Kerberos and JWT all use the "authorization" header, that's why the existing tests did not reveal this bug.

Proposed solution: Examine all headers in the requestHeadersWhitelist setting of kibana, and copy them over. Also, pay attention to the default "authorization" header when this setting is empty. 

Needs to be fixed in the next release.

@faxm0dem Thanks for reporting!

**Comment by jochenkressin** [comment] 2017-05-06 15:52
Can you please try this snapshot for Kibana 5.3.1:

https://cdn.filestackcontent.com/E3BS0gR1QSW2Qz21OzYR

If you also have Basic Auth enabled (e.g. for the Kibana server user), make sure to have proxy auth first, and Basic Auth second in sg_config.yml.

**Comment by faxm0dem** [comment] 2017-05-07 10:04
hmmm kibana doesn't manage to connect. Maybe it's because kibana 5.3.1 isn't compatible with ES 5.3.2?

**Comment by jochenkressin** [comment] 2017-05-07 10:16
Sorry, I was under the impression that you use 5.3.1 based on another bug report you issued. KI 5.3.1 against ES 5.3.2 should work, you will just see a warning in the Kibana log. But we can build a snapshot for 5.3.2 as well.

However, I just tried the KI 5.3.1 / ES 5.3.2 scenario locally, and it works here. Can you please share 

* the Kibana log where connection to ES fails
* the kibana.yml file
* the sg_config file

Anything suspicious in the ES log files?

**Comment by faxm0dem** [comment] 2017-05-08 07:29
Sorry, it was a problem on my end: ES had died for some reason.
Your modified version works!
I can list tenants, and the RO/RW permissions seem to work as expected.

Thanks very much for fixing this so quickly

**Comment by faxm0dem** [comment] 2017-05-08 07:36
I think I spoke too quickly: the tenant list works, the kibana indices are created, but when trying to access them in "Discovery" tab, I get the following error:

```
Config: Error 404 Not Found: [document_missing_exception] [config][5.3.1]: document missing, with { index_uuid="6ZAMNlX-SSKDBBebh86Tww" & shard="0" & index=".kibana_1865400007_sandbox" }
```

**Comment by faxm0dem** [comment] 2017-05-08 07:50
So the error above appears when trying to configure the default index pattern.
And here's the corresponding kibana log entry:

```JSON
{
  "type": "response",
  "@timestamp": "2017-05-08T07:38:36Z",
  "tags": [],
  "pid": 9615,
  "method": "post",
  "statusCode": 404,
  "req": {
    "url": "/api/kibana/settings/defaultIndex",
    "method": "post",
    "headers": {
      "host": "localhost:8200",
      "x-authenticated-user": "faxmodem",
      "x-forwarded-server": "kibana.example.com, 127.0.0.1",
      "x-forwarded-host": "kibana.example.com, 127.0.0.1:8000",
      "x-forwarded-for": "10.0.230.72, 127.0.0.1",
      "via": "1.1 kibana.example.com, 1.1 127.0.0.1:8000",
      "cas-user": "faxmodem@example.com",
      "referer": "https://kibana.example.com/app/kibana",
      "kbn-version": "5.3.1",
      "content-type": "application/json;charset=utf-8",
      "dnt": "1",
      "accept-encoding": "gzip, deflate",
      "accept-language": "en,en-US;q=0.8,fr;q=0.5,de;q=0.3",
      "accept": "application/json, text/plain, */*",
      "user-agent": "Mozilla/5.0 (X11; Linux x86_64; rv:45.0) Gecko/20100101 Firefox/45.0",
      "x-authenticated-group": "common",
      "connection": "Keep-Alive",
      "content-length": "18",
      "sg_tenant": "sandbox"
    },
    "remoteAddress": "127.0.0.1",
    "userAgent": "127.0.0.1",
    "referer": "https://kibana.example.com/app/kibana"
  },
  "res": {
    "statusCode": 404,
    "responseTime": 30,
    "contentLength": 9
  },
  "message": "POST /api/kibana/settings/defaultIndex 404 30ms - 9.0B"
}
```

### kibana.yml
```YAML
elasticsearch.password: changeme
elasticsearch.preserveHost: true
elasticsearch.requestHeadersWhitelist: ["sg_tenant", "x-authenticated-user", "x-authenticated-group", "authorization", "x-forwarded-for", "x-forwarded-server"]
elasticsearch.ssl.verify: false
elasticsearch.url: https://localhost:9200
elasticsearch.username: changeme
kibana.index: .changeme
searchguard.basicauth.enabled: false
searchguard.multitenancy.enabled: true
searchguard.multitenancy.tenants.enable_global: true
searchguard.multitenancy.tenants.enable_private: true
server.host: 127.0.0.1
server.port: 8200
```

### sg_config.yaml
```YAML
---
searchguard:
  dynamic:
    kibana:
      multitenancy_enabled: true
      server_username: kibana
      index: ".kibana"
      do_not_fail_on_forbidden: false
    http:
      anonymous_auth_enabled: false
      xff:
        enabled: true
        remoteIpHeader: X-Forwarded-For
        trustedProxies: 127.0.0.1
        internalProxies: 127.0.0.1
    authc:
      kerberos_auth_domain:
        enabled: true
        order: 5
        http_authenticator:
          type: kerberos
          challenge: true
          config:
            krb_debug: true
            strip_realm_from_principal: true
        authentication_backend:
          type: noop
      basic_internal_auth_domain:
        enabled: true
        order: 4
        http_authenticator:
          type: basic
          challenge: false
        authentication_backend:
          type: intern
      proxy_auth_domain:
        enabled: true
        order: 1
        http_authenticator:
          type: proxy
          challenge: false
          config:
            user_header: x-authenticated-user
            roles_header: x-authenticated-group
        authentication_backend:
          type: noop
      host_auth_domain:
        enabled: false
      jwt_auth_domain:
        enabled: false
      clientcert_auth_domain:
        enabled: true
        order: 3
        http_authenticator:
          type: clientcert
          challenge: false
        authentication_backend:
          type: noop
      ldap:
        enabled: false
    authz:
      roles_from_myldap:
        enabled: false
```

**Comment by jochenkressin** [comment] 2017-05-09 11:53
I'm a bit confused about the configs, with these settings you should see a warning message on the tenants tab, because in sg_config you set:

- server_username: kibana
- index: ".kibana"

And in kibana.yml you set:

- elasticsearch.username: changeme
- kibana.index: .changeme

The value(s) of these settings must match on ES and KI side. The plugin should check this when opening the tenants tab, and print a warn message if the settings differ. Are you sure the configs you posted are the correct ones, or do I miss something here?

**Comment by faxm0dem** [comment] 2017-05-09 11:57
sorry, I used sed to change the password, and it also changed the username.
The setting is okay

**Comment by jochenkressin** [comment] 2017-05-09 12:17
Ok, understood. To pinpoint the problem we will send you a snapshot for ES 5.3.2, to rule out any issues that might stem from the version difference.

Is this a test cluster? Because if it is, I'd like you to delete the data directory or at least any already created Kibana index. Would that be possible on your side?

**Comment by faxm0dem** [comment] 2017-05-09 12:25
It's the prepoduction cluster, so I can't delete the data.
However, I can with some additional work respawn a test cluster

**Comment by jochenkressin** [comment] 2017-05-09 12:42
Ok. So I assume that you already have some objects in the default .kibana index, right? If that is the case, are you able to access those when choosing the "Global" tenant?

**Comment by faxm0dem** [comment] 2017-05-09 12:55
yes, the Global tenant works fine.
all other tenants, Private included fail when trying to save a default index-pattern:

```
Config: Error 404 Not Found: [document_missing_exception] [config][5.3.1]: document missing, with { indexuuid="dnq3Ujp1S7-5XLzzinl76w" & shard="0" & index=".kibana-460255123_foo" }
```

**Comment by faxm0dem** [comment] 2017-05-10 13:45
I have a test cluster up&running with the same symptoms. I will try to delete all kibana indices and report back.

**Comment by jochenkressin** [comment] 2017-05-11 08:45
I'm able to reproduce the behavior now with the setup and configs you provided. I'll investigate and report back soon.

**Comment by jochenkressin** [comment] 2017-05-11 09:50
Can you please try this Kibana plugin snapshot with 5.3.2 for both Kibana and Elastic?

https://cdn.filestackcontent.com/PdYbw24hRVSI5hp00bMB

We still need to investigate the root cause of your issue though. KI 5.3.1 should work with ES 5.3.2, regardless of the warning in the logs.

**Comment by faxm0dem** [comment] 2017-05-11 11:52
It seems to work on my test cluster, but not on the production one.
In all cases I don't have any 500 errors anymore.
I'm currently investigating

**Comment by jochenkressin** [comment] 2017-05-11 12:18
Thanks for your help here!

We're tracking this issue now in:

https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/8
https://github.com/floragunncom/search-guard-module-kibana-multitenancy/issues/9

**Comment by faxm0dem** [comment] 2017-05-11 13:21
I have an odd issue on the production cluster: when adding a new index pattern to the *Global* tenant, I get the following in the ES log as soon as I click on *Create*:

```
No cluster-level perm match for User [name=faxmodem, roles=[common]] [IndexType [index=.kibana, type=index-pattern]] [Action [indices:data/write/bulk]] [RolesChecked [sg_role_myorg, sg_role_kibana_god]]
No permissions for {}
```

This doesn't happen for any other tenant

**Comment by faxm0dem** [comment] 2017-05-16 07:52
@jochenkressin sorry for poking you but shall I open a different issue for the *Global* tenant behaviour?

**Comment by jochenkressin** [comment] 2017-05-16 09:34
@faxm0dem This is actually expected, but wrongly documented behavior. Since ES 5.3, you also need to have bulk write permissions on the Kibana index. The reason why this happens only for the Global tenant is that this tenant refers to the original .kibana index and that it is written by the configured Kibana server user. For all other tenants, we re-write the original request, and these re-written requests have the respective permissions implicitly, including the bulk permissions.

We will update the docs on this to make the behaviour more clear.

I'd like to keep this issue open until v3 of the Kibana module, including proxy auth support, will be released.

Thanks for your input!

**Comment by faxm0dem** [comment] 2017-05-16 11:30
ack, thanks for the clarification

**Comment by floragunncom** [comment] 2017-05-30 20:43
Will close this, status will be tracked here https://github.com/floragunncom/search-guard-kibana-plugin/issues/23

**Closed by floragunncom** 2017-05-30 20:43 UTC
Labels: bug
