### ISSUE TITLE
delete_by_query: No permissions für indices:data/read/scroll

### ISSUE THREAD

**Issue by misterunknown** [floragunncom/search-guard#445] opened 2018-02-02 14:03 UTC
Hi.

we try to use the `delete_by_query` function, but get a 403 error message. Some information:

* Elasticsearch 5.6.4
* SafeGuard 5.6.4-16
* jre1.8.0_91
* only one node in the cluster
* [sg_roles.yaml](https://pastebin.com/0hXRWahs)
* [sg_roles_mapping.yaml](https://pastebin.com/xdpLr80D)
* [sg_internal_users.yaml](https://pastebin.com/kFwMRKY9)
* [sg_action_groups.yaml](https://pastebin.com/dP5zAkwK)

This is the command line:
```
$ curl --user evo-admin:XXX -XPOST http://localhost:9200/online/cms/_delete_by_query -d '{"query":{"match_all":{}}}'
{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for indices:data/read/scroll"}],"type":"security_exception","reason":"no permissions for indices:data/read/scroll"},"status":403}
```
The user evo-admin should have the `indices:data/read/scroll` permission, because his role contains the `INDICES_ALL` action group. Any ideas how to fix this?

Cheers,
Marco

**Comment by floragunncom** [comment] 2018-02-02 18:28
duplicate of https://github.com/floragunncom/search-guard/issues/377#issuecomment-340217647 and https://github.com/floragunncom/search-guard/issues/319

Delete by query use internally search scrolling. 
Add "indices:data/read/scroll*" to cluster permissions.

**Closed by floragunncom** 2018-02-02 18:28 UTC
