### ISSUE TITLE
Restore not working when search guard is enabled 

### ISSUE THREAD

**Issue by kanumilliveena** [floragunncom/search-guard#222] opened 2016-10-18 20:49 UTC
Im trying to restore a snapshot, Im getting below error:

curl -u admin:password -XPOST "localhost:9200/_snapshot/backup_16OCT2016/snapshot_1/_restore" -d '{
"indices": "search",
"ignore_unavailable": true,
"include_global_state": false
}

{"error":{"root_cause":[{"type":"security_exception","reason":"no permissions for cluster:admin/snapshot/restore"}]
,"type":"security_exception","reason":"no permissions for cluster:admin/snapshot/restore"},"status":403}

 Seeing below error in syslog:

elasticsearch[19411]: [2016-10-18 12:41:24,291][WARN ][com.floragunn.searchguard.configuration.PrivilegesEvaluator] cluste
r:admin/snapshot/restore is not allowed for a regular user.

Tried role mappings, but no luck? Any help is appreciated

**Comment by floragunncom** [comment] 2016-10-19 16:33
duplicate of https://github.com/floragunncom/search-guard/issues/116

**Closed by floragunncom** 2016-10-19 16:33 UTC

**Comment by floragunncom** [comment] 2016-10-19 16:34
docs moved to https://github.com/floragunncom/search-guard-docs/blob/master/snapshots.md
