### ISSUE TITLE
Problem with FLS

### ISSUE THREAD

**Issue by armenak** [floragunncom/search-guard#280] opened 2017-01-18 22:37 UTC
Hello,

The environment is: Java 1.8, ES 5.1.1, SG 5.5.1-10, SG DSL/FSL 5.1.5, Kibana 5.1.1, and SG plugin for Kibana searchguard-kibana-alpha-5.1.1.

I've successfully setup the DLS, but having problem seeing data after I configure FLS.  Log and config files are attached.

For example this configuration does not work, however, if I remove the FLS config, than the DLS is working as expected.

<pre>
sg_role_armenak:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
      _fls_: 
        - 'host'
        - 'type'
    '?kibana':
      '*':
        - KIBANA_SERVER
</pre>
Thanks,
Armenak

[elasticsearch.log.txt](https://github.com/floragunncom/search-guard/files/715214/elasticsearch.log.txt)
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/715216/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/715218/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/715217/sg_internal_users.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/715220/sg_roles.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/715219/sg_roles_mapping.yml.txt)

**Comment by floragunncom** [comment] 2017-01-18 22:52
try adding '_type' to the allowed fields. You can not filter on fields in DLS when not allowed in FLS.

**Comment by armenak** [comment] 2017-01-18 23:26
Unfortunately, it did not work.

sg_role_armenak:
  cluster:
    - cluster:monitor/main
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - READ
        - SEARCH
        - indices:data/read/field_stats
      _dls_: '{"term" : {"_type" : "audit"}}'
      _fls_:
         - '_type'
         - 'type'
         - 'host'
    '?kibana':
      '*':
        - KIBANA_SERVER

**Comment by floragunncom** [comment] 2017-01-19 10:23
What ist the result and what did you expect?

**Comment by armenak** [comment] 2017-01-19 10:59
Strange. I thought I explained my expectations in the initial email ...

**Comment by floragunncom** [comment] 2017-01-19 11:13
What shows `curl -sSk https://elasticsearchserver:9200/logstash-*/_search?pretty` which DLS and FLS applied? Did it return the expected result?

**Comment by floragunncom** [comment] 2017-01-19 13:13
can you try this (this works for me locally)

<pre>
sg_role_armenak:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    'logstash-*':
      '*':
        - READ
        - 'indices:admin/mappings/fields/get*'
      _dls_: '{"term" : {"_type" : "audit"}}'
      _fls_:
         - '_type'
         - 'type'
         - 'host'
    '?kibana':
      '*':
        - READ
        - WRITE
        - 'indices:admin/mappings/fields/get*'
        - 'indices:admin/refresh*'
</pre>

**Comment by armenak** [comment] 2017-01-19 18:17
>> What shows curl -sSk -u user:pass https://elasticsearchserver:9200/logstash-*/_search?pretty >> which DLS and FLS applied? Did it return the expected result?
No, it does not return expected result. The output is below:
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for indices:data/read/search"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for indices:data/read/search"
  },
  "status" : 403
}

**Comment by armenak** [comment] 2017-01-19 18:18
>> can you try this (this works for me locally)
I tried and I am getting the following error in Kibana:
Discover: [security_exception] no permissions for indices:data/read/field_stats

**Comment by armenak** [comment] 2017-01-20 19:33
ping

**Comment by floragunncom** [comment] 2017-01-23 09:35
Cannot reproduce it. Please post logs on DEBUG level where "no permissions for indices:data/read/search" as well as "no permissions indices:data/read/field_stats" is logged.

**Comment by armenak** [comment] 2017-01-25 00:27
I have installed ES and SG from scratch and now I do not see "no permission error". However, SG behaves differently now. When FLS is applied, I can't see any data in Kibana (the message on the screen says "No results found"). When I remove FLS settings and keep only DLS, than I can see the data.

Config files and ES log file are attached.
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/728269/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/728267/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/728268/sg_internal_users.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/728266/sg_roles.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/728270/sg_roles_mapping.yml.txt)

**Comment by armenak** [comment] 2017-01-25 00:34
I have installed ES and SG from scratch and now I do not see "no permission error". However, SG behaves differently now. When FLS is applied, I can't see any data in Kibana. When I remove FLS settings and keep only DLS, than I can see the data.

The log and configuration files are attached.

[elasticsearch.log.txt](https://github.com/floragunncom/search-guard/files/728305/elasticsearch.log.txt)
[sg_action_groups.yml.txt](https://github.com/floragunncom/search-guard/files/728306/sg_action_groups.yml.txt)
[sg_config.yml.txt](https://github.com/floragunncom/search-guard/files/728304/sg_config.yml.txt)
[sg_internal_users.yml.txt](https://github.com/floragunncom/search-guard/files/728307/sg_internal_users.yml.txt)
[sg_roles.yml.txt](https://github.com/floragunncom/search-guard/files/728302/sg_roles.yml.txt)
[sg_roles_mapping.yml.txt](https://github.com/floragunncom/search-guard/files/728303/sg_roles_mapping.yml.txt)

**Comment by floragunncom** [comment] 2017-01-25 12:02
Thats strange in two ways: First question is why does the behavior changed after a complete reinstall? Second question is why do you see no data? While investigating https://github.com/floragunncom/search-guard/issues/281 i tested your scenario locally (including dls and fls) and it worked well. I recommend to enable the browsers web developer tools and figure out which request is the problematic one 

Example: 
![kibtrace](https://cloud.githubusercontent.com/assets/11678154/22289943/73b2e76e-e2fe-11e6-86fb-abc6c6901741.png)

**Comment by armenak** [comment] 2017-01-31 00:32
Unfortunately, still not working. When I remove fls settings everything is working just fine.
![fls](https://cloud.githubusercontent.com/assets/3421052/22447814/aa03f39e-e709-11e6-9ebe-0d4623588755.png)


Attaching the screenshot.
The configuration is below:
sg_role_as:
  cluster:
    - CLUSTER_MONITOR
    - CLUSTER_COMPOSITE_OPS
  indices:
    'as-*':
      '*':
        - READ
        - indices:data/read/field_stats
        - indices:data/read/*
      _dls_: '{"term" : {"_type" : "audit"}}'
      _fls_:
        - '_type'
        - 'type'
        - 'host'
    '?kibana':
      '*':
        - KIBANA_SERVER


The relevant exception in the log file is below:
[2017-01-30T16:23:39,575][DEBUG][c.f.s.c.PrivilegesEvaluator] For index ?kibana remaining requested indextype: [IndexType [index=.monitoring-es-2-2017.01.20, type=*], IndexType [index=auditlog, type=*], IndexType [index=logstash-syslog-2017.01.30, type=*], IndexType [index=logstash-audit-2017.01.30, type=*], IndexType [index=.monitoring-data-2, type=*], IndexType [index=logstash-syslog-2017.01.27, type=*], IndexType [index=logstash-syslog-2017.01.28, type=*], IndexType [index=logstash-syslog-2017.01.25, type=*], IndexType [index=logstash-syslog-2017.01.26, type=*], IndexType [index=logstash-audit-2017.01.27, type=*], IndexType [index=logstash-audit-2017.01.28, type=*], IndexType [index=logstash-audit-2017.01.25, type=*], IndexType [index=logstash-syslog-2017.01.29, type=*], IndexType [index=logstash-audit-2017.01.26, type=*], IndexType [index=searchguard, type=*], IndexType [index=logstash-audit-2017.01.29, type=*]]
[2017-01-30T16:23:39,575][INFO ][c.f.s.c.PrivilegesEvaluator] No perm match for User [name=armenak, roles=[]] [IndexType [index=as-2017.01.30, type=*], IndexType [index=.monitoring-es-2-2017.01.20, type=*], IndexType [index=auditlog, type=*], IndexType [index=logstash-syslog-2017.01.30, type=*], IndexType [index=logstash-audit-2017.01.30, type=*], IndexType [index=.monitoring-data-2, type=*], IndexType [index=logstash-syslog-2017.01.27, type=*], IndexType [index=logstash-syslog-2017.01.28, type=*], IndexType [index=logstash-syslog-2017.01.25, type=*], IndexType [index=as-2017.01.31, type=*], IndexType [index=logstash-syslog-2017.01.26, type=*], IndexType [index=logstash-audit-2017.01.27, type=*], IndexType [index=logstash-audit-2017.01.28, type=*], IndexType [index=logstash-audit-2017.01.25, type=*], IndexType [index=logstash-syslog-2017.01.29, type=*], IndexType [index=logstash-audit-2017.01.26, type=*], IndexType [index=searchguard, type=*], IndexType [index=.kibana, type=*], IndexType [index=logstash-audit-2017.01.29, type=*]] [Action [indices:data/read/search]] [RolesChecked [sg_own_index, sg_public, sg_role_as]]
[2017-01-30T16:23:39,575][DEBUG][c.f.s.f.SearchGuardFilter] no permissions for indices:data/read/search
[2017-01-30T16:23:39,576][DEBUG][r.suppressed             ] path: /_search, params: {}
org.elasticsearch.ElasticsearchSecurityException: no permissions for indices:data/read/search
	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:160) ~[?:?]
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:171) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:145) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:87) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.client.node.NodeClient.executeLocally(NodeClient.java:75) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.client.node.NodeClient.doExecute(NodeClient.java:64) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.client.support.AbstractClient.execute(AbstractClient.java:403) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.client.support.AbstractClient.search(AbstractClient.java:530) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.action.search.RestSearchAction.lambda$prepareRequest$0(RestSearchAction.java:83) ~[elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.BaseRestHandler.handleRequest(BaseRestHandler.java:82) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.RestController.executeHandler(RestController.java:243) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.RestController$RestHandlerFilter.process(RestController.java:326) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:307) [elasticsearch-5.1.1.jar:5.1.1]
	at com.floragunn.searchguard.filter.SearchGuardRestFilter.process(SearchGuardRestFilter.java:107) [search-guard-5-5.1.1-10.jar:?]
	at org.elasticsearch.rest.RestController$ControllerFilterChain.continueProcessing(RestController.java:310) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.rest.RestController.dispatchRequest(RestController.java:203) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.http.HttpServer.dispatchRequest(HttpServer.java:113) [elasticsearch-5.1.1.jar:5.1.1]
	at org.elasticsearch.http.netty4.Netty4HttpServerTransport.dispatchRequest(Netty4HttpServerTransport.java:507) [transport-netty4-client-5.1.1.jar:5.1.1]
	at com.floragunn.searchguard.http.SearchGuardNonSslHttpServerTransport.dispatchRequest(SearchGuardNonSslHttpServerTransport.java:62) [search-guard-5-5.1.1-10.jar:?]
	at org.elasticsearch.http.netty4.Netty4HttpRequestHandler.channelRead0(Netty4HttpRequestHandler.java:69) [transport-netty4-client-5.1.1.jar:5.1.1]
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:105) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at org.elasticsearch.http.netty4.pipelining.HttpPipeliningHandler.channelRead(HttpPipeliningHandler.java:66) [transport-netty4-client-5.1.1.jar:5.1.1]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageCodec.channelRead(MessageToMessageCodec.java:111) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:102) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267) [netty-codec-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.ChannelInboundHandlerAdapter.channelRead(ChannelInboundHandlerAdapter.java:86) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:351) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1334) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:373) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:359) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:926) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:129) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:651) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysPlain(NioEventLoop.java:536) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:490) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:450) [netty-transport-4.1.6.Final.jar:4.1.6.Final]
	at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:873) [netty-common-4.1.6.Final.jar:4.1.6.Final]
	at java.lang.Thread.run(Thread.java:745) [?:1.8.0_111]

**Comment by floragunncom** [comment] 2017-01-31 10:43
You are only allowed to query 'as-*' indices, so try

<pre>
GET es_*/_search
{
  "query": {
    "match_all": {}
  }
}
</pre>

**Comment by armenak** [comment] 2017-01-31 21:07
Thank you. It is strange, though. With the query you suggested  it is working as expected. I get the data and I see only fields I indicated. However, in the Discovery mode I still see no data. No errors in the log file.

**Comment by floragunncom** [comment] 2017-02-01 09:59
It's all about index patterns.

This issue seems not to be a bug, so i'll close it. For discussions and community support pls. go to the Search Guard google group.

**Closed by floragunncom** 2017-02-01 09:59 UTC
