### ISSUE TITLE
Unable to Install Demo Configuration on Elasticsearch Docker Image

### ISSUE THREAD

**Issue by arvalaan** [floragunncom/search-guard#385] opened 2017-09-07 13:13 UTC
[elasticsearch@es-cluster-es-client-1 ~]$ bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.5.1-15
-> Downloading com.floragunn:search-guard-5:5.5.1-15 from maven central
[=================================================] 100%??
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
@     WARNING: plugin requires additional permissions     @
@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
* java.io.FilePermission /proc/sys/net/core/somaxconn read
* java.lang.RuntimePermission accessClassInPackage.sun.misc
* java.lang.RuntimePermission accessClassInPackage.sun.nio.ch
* java.lang.RuntimePermission accessClassInPackage.sun.security.x509
* java.lang.RuntimePermission accessDeclaredMembers
* java.lang.RuntimePermission getClassLoader
* java.lang.RuntimePermission loadLibrary.*
* java.lang.RuntimePermission setContextClassLoader
* java.lang.RuntimePermission shutdownHooks
* java.lang.reflect.ReflectPermission suppressAccessChecks
* java.security.SecurityPermission getProperty.ssl.KeyManagerFactory.algorithm
* java.security.SecurityPermission setProperty.ocsp.enable
* java.util.PropertyPermission com.sun.security.enableCRLDP write
* java.util.PropertyPermission es.set.netty.runtime.available.processors write
* java.util.PropertyPermission java.security.debug write
* java.util.PropertyPermission java.security.krb5.conf write
* java.util.PropertyPermission javax.security.auth.useSubjectCredsOnly write
* java.util.PropertyPermission sun.nio.ch.bugLevel write
* java.util.PropertyPermission sun.security.krb5.debug write
* java.util.PropertyPermission sun.security.spnego.debug write
* javax.security.auth.AuthPermission doAs
* javax.security.auth.AuthPermission modifyPrivateCredentials
* javax.security.auth.kerberos.ServicePermission * accept
See http://docs.oracle.com/javase/8/docs/technotes/guides/security/permissions.html
for descriptions of what these permissions allow and the associated risks.
-> Installed search-guard-5
[elasticsearch@es-cluster-es-client-1 ~]$ cd plugins/search-guard-5/tools/
[elasticsearch@es-cluster-es-client-1 tools]$ chmod a+x install_demo_configuration.sh
[elasticsearch@es-cluster-es-client-1 tools]$ ./install_demo_configuration.sh
## Search Guard Demo Installer ##
Warning: Do not use on production or public reachable systems
Continue? [y/N] y
This script maybe require your root password for 'sudo' privileges
./install_demo_configuration.sh: line 39: sudo: command not found
Unable to determine elasticsearch config directory. Quit.
[elasticsearch@es-cluster-es-client-1 tools]$
______________________________________________________________________

With a fresh Docker image from Elastic, running the script doesn't work. Commenting out the RPM script part will allow the script to run but I seem to still have issues getting it up and running throughout the whole cluster.

**Comment by floragunncom** [comment] 2017-09-07 13:24
Which elasticsearch docker image do you use?

**Comment by arvalaan** [comment] 2017-09-07 13:26
@floragunncom Apologies, should've included that. I'm using: docker.elastic.co/elasticsearch/elasticsearch:5.5.1

**Comment by floragunncom** [comment] 2017-09-07 13:29
thx, will look into it

**Comment by stephenyeargin** [comment] 2017-10-02 15:12
Root cause is:

```
 ./install_demo_configuration.sh: line 39: sudo: command not found
```

Which is expected-ish, given the docker image for Elasticsearch doesn't come with the `sudo` command by default. It runs as a privileged user called `elasticsearch`, but I cannot find any documentation on how to switch to `root` and then install the plugin.

The shell script should probably do a `command -v sudo` and verify there is output. If not, bail with a helpful error message about how to get around this (TBD).

**Comment by floragunncom** [comment] 2017-10-02 15:24
@stephenyeargin can you prepare a PR for that? I would be very happy to merge it.

**Comment by PDS42** [comment] 2017-10-20 09:48
Experiencing the exact same issue with ```docker.elastic.co/elasticsearch/elasticsearch:5.6.2``` and ```search-guard-5:5.6.2-16```. What are my options here? I'm struggling to find a solution!

**Comment by floragunncom** [comment] 2017-10-21 22:38
@PDS42 @stephenyeargin @arvalaan  Pls check if this script works for you https://gist.github.com/floragunncom/4a28c59933fda662100393c75687bf2c

If yes it will be included in the next release

**Comment by PDS42** [comment] 2017-10-23 09:34
Thanks for the quick reply. I tried to test this, but I cannot run my container without this error: ```Unable to read /usr/share/elasticsearch/config/keystore.jks (/usr/share/elasticsearch/config/keystore.jks). Please make sure this files exists and is readable regarding to permissions.```
![screen shot 2017-10-23 at 11 30 56 am](https://user-images.githubusercontent.com/11089426/31881995-b08cf956-b7e5-11e7-95f5-20801e831132.png)

I saw in other issues that you were referring to ```https://github.com/floragunncom/search-guard-ssl/blob/master/example-pki-scripts/``` to generate certs, as I assume that I'm missing them, but how does that translate to Docker? Do I need to run those through my Dockerfile everytime, or in another way? Is this still relevant? Thank you for your time, I hope you'll be able to help me though this so I can test your script!

**Comment by floragunncom** [comment] 2017-10-23 09:41
Can you post your Dockerfile so i can try to reproduce it?

**Comment by PDS42** [comment] 2017-10-23 09:46
Dockerfile:

```FROM docker.elastic.co/elasticsearch/elasticsearch:5.6.2

USER root
WORKDIR /usr/share/elasticsearch/

ADD elasticsearch.yml config/
ADD limits.conf /
ADD jvm.conf /

ENV ES_HOSTNAME localhost
ENV ES_PORT 9200

RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
RUN chown -R elasticsearch:elasticsearch data
# install security plugin

RUN bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.6.2-16
COPY install_demo_configuration.sh plugins/search-guard-5/tools/
RUN chmod +x plugins/search-guard-5/tools/install_demo_configuration.sh && ./plugins/search-guard-5/tools/install_demo_configuration.sh


USER elasticsearch

EXPOSE 9200```

```elasticsearch.yml``` in case you needed it aswell:

```network.host: [_eth0_, _local_]
cluster.name: monpetitcluster
node.name: "Sick Ranchez"
http.cors.enabled: true
http.cors.allow-origin: "*"
http.cors.allow-methods: OPTIONS, HEAD, GET, POST, PUT, DELETE
http.cors.allow-headers: "X-Requested-With,X-Auth-Token,Content-Type, Content-Length, Authorization"

#Disable xpack security features
xpack.security.enabled: false
# searchguard

searchguard.ssl.transport.keystore_filepath: keystore.jks
searchguard.ssl.transport.keystore_password: changeit
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: changeit
```

**Comment by floragunncom** [comment] 2017-10-23 14:55
If you use "install_demo_configuration.sh" you should not modify the elasticsearch.yml yourself afterwards (cause the script will set all config items). If you decide to makes changes anyhow you should first look on the modification made by the script and then adapt them accordingly. The script does also place certificates into the config folder which means that you also should not mount a external config folder into the docker container (or do similar things). You must not use the example-pki-scripts or any other certificates together with "install_demo_configuration.sh".

**Comment by PDS42** [comment] 2017-10-23 15:21
I did not plan to use the demo script, but I just wanted to test auth before fully commiting to an install! 

My root problem being (the reason why I switched from ```sgadmin.sh``` to the demo one):

```ERR: Parsing failed.  Reason: Specify at least -ks or -cert``` when I run ./sgadmin.sh 

I do not have the certs to include them in the params, so my question is: can I just copy the whole content of `example-pki-scripts` in a new folder on my container, and run the `example.sh` Or do I need some other config? Thank you for your time, much appreciated.

**Comment by floragunncom** [comment] 2017-11-10 17:24
here is more recent version which should work in any environment. this will be included in the next release: https://github.com/floragunncom/search-guard/blob/5.6.0/tools/install_demo_configuration.sh

**Comment by floragunncom** [comment] 2017-12-13 12:13
no response, assume solved

**Closed by floragunncom** 2017-12-13 12:13 UTC

**Comment by AndriyShepitsen** [comment] 2018-04-24 19:04
Thank you, very much guys. It does work - I just needed to add ``-y`` to running a script:

   
```
FROM docker.elastic.co/elasticsearch/elasticsearch:5.5.2
USER root
WORKDIR /usr/share/elasticsearch/

ENV ES_HOSTNAME localhost
ENV ES_PORT 9200

RUN chown elasticsearch:elasticsearch config/elasticsearch.yml
RUN chown -R elasticsearch:elasticsearch data
# install security plugin

RUN bin/elasticsearch-plugin install -b com.floragunn:search-guard-5:5.5.2-16
COPY ./safe-guard/install_demo_configuration.sh plugins/search-guard-5/tools/
RUN chmod +x plugins/search-guard-5/tools/install_demo_configuration.sh && ./plugins/search-guard-5/tools/install_demo_configuration.sh -y


USER elasticsearch

EXPOSE 9200
```
