### ISSUE TITLE
Hot config reloading not working

### ISSUE THREAD

**Issue by RachelMannion** [floragunncom/search-guard#199] opened 2016-08-15 10:42 UTC
Seach Guard version=2.3.4.4
 elasticsearch-2.3.4
1 node cluster

java version "1.8.0_101"
Java(TM) SE Runtime Environment (build 1.8.0_101-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.101-b13, mixed mode)

CentOS Linux release 7.1.1503

I add user "coffee" to the sg_internal_users.yml file
I run the command 
 plugins/search-guard-2/tools/sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -ks /apps/omn/elastic/elasticsearch/config/kirk-keystore.jks -ts /apps/omn/elastic/elasticsearch/config/truststore.jks  -nhnv -h hostname -icl  -t internalusers -f plugins/search-guard-2/sgconfig/ sg_internal_users.yml

I run  curl -XGET 'http://hostname:9200/_searchguard/authinfo' -u coffee -Ss -k
Nothing is returned

I run the retrieve command 
plugins/search-guard-2/tools/sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -ks plugins/search-guard-2/sgconfig/kirk-keystore.jks -ts plugins/search-guard-2/sgconfig/truststore.jks  -nhnv -h hostname -icl -r

"coffee" user is included in yml file returned from retrieve command

I restart elastic search
I run  curl -XGET 'http://hostname:9200/_searchguard/authinfo' -u coffee -Ss -k
coffee user is returned

I attach DEBUG on for  com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction
for
plugins/search-guard-2/tools/sgadmin.sh -cd plugins/search-guard-2/sgconfig/ -ks /apps/omn/elastic/elasticsearch/config/kirk-keystore.jks -ts /apps/omn/elastic/elasticsearch/config/truststore.jks  -nhnv -h hostname -icl  -t internalusers -f plugins/search-guard-2/sgconfig/ sg_internal_users.yml
and for 

curl -XGET 'http://hostname:9200/_searchguard/authinfo' -u coffee -Ss -k

[elk_authreq.log.txt](https://github.com/floragunncom/search-guard/files/417899/elk_authreq.log.txt)
[elk_update.log.txt](https://github.com/floragunncom/search-guard/files/417900/elk_update.log.txt)

**Comment by floragunncom** [comment] 2016-08-18 20:12
This is very likely fixed with 2.3.4.5. Can you check if the issue is fixed with that version? 

And it seems also that your ``curl`` command is wrong because the password is missing (and maybe you need to use https instead of http). Normally it should look like: ``curl -XGET 'http(S)://hostname:9200/_searchguard/authinfo' -u coffee:PASSWORD -Ss -k``

**Comment by floragunncom** [comment] 2016-09-11 21:14
No feedback, assume fixed. If not pls. reopen this ticket or create a new one.

**Closed by floragunncom** 2016-09-11 21:14 UTC
