### ISSUE TITLE
Can't restore or reindex searchguard index

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard#519] opened 2018-07-09 21:17 UTC
**Search-guard for elastic search 6.3.0**

I have multi tenancy enabled with internal user database but I have two clusters and I need to either reindex or restore the configuration of one cluster to another cluster to avoid duplication of work , i need to restore all the .kibana_* indices , plus the searchguard index in order to be able to give users smooth login experience to both clusters.

Is it possible to achieve. 

I have successfully done it for .kibana|_* indices but the searchguard copy process still need to be done. how can we do that.

With admin user , with all access , I can neither reindex searchguard index to the other cluster nor can 
I restore from recent snapshot.

**Comment by floragunncom** [comment] 2018-07-09 21:41
The Search Guard index contains sensitive data so it is not possible to restore it from a snapshot for regular users. But that's exactly what the admin certificate is for: It grants full access to a Search Guard secured cluster without any limitations. So if you want to restore the Search Guard index, the easiest way would be to use the admin cert.

I'm closing this issue because it is not a bug. For general questions like this, please use the Google Groups. Thanks!

**Closed by floragunncom** 2018-07-09 21:41 UTC

**Comment by iahmad-khan** [comment] 2018-07-10 08:40
still have problem:

```
curl -u admin --insecure --cert truststore.jks --key ./kirk-keystore.jks -XPOST 'localhost:9200/_snapshot/backups/snapshot_10-07-2018/_restore?pretty'
Enter host password for user 'admin':
{
  "error" : {
    "root_cause" : [
      {
        "type" : "security_exception",
        "reason" : "no permissions for [cluster:admin/snapshot/restore] and User [name=admin, roles=[admin], requestedTenant=null]"
      }
    ],
    "type" : "security_exception",
    "reason" : "no permissions for [cluster:admin/snapshot/restore] and User [name=admin, roles=[admin], requestedTenant=null]"
  },
  "status" : 403
}

```
