### ISSUE TITLE
unable to get count  when i run this through browser   "IP:9200/_cat/count"

### ISSUE THREAD

**Issue by madhusudand** [floragunncom/search-guard#32] opened 2015-07-08 13:43 UTC
I am new to searchguard 
Logged in as admin through browser and getting following error when i hit this url "IP:9200/_cat/count":
{"error":"RuntimeException[java.lang.RuntimeException: Attempt from null to _all indices for indices:data/read/count and User [name=admin, roles=[admin]]]; nested: RuntimeException[Attempt from null to _all indices for indices:data/read/count and User [name=admin, roles=[admin]]]; ","status":500}

Configuration: admin roll. no filter is executed.
Thanks in advance..

**Comment by madhusudand** [comment] 2015-07-14 05:17
Any solutions for the above mentioned query????

**Comment by floragunncom** [comment] 2015-07-19 21:12
pls. provide your elasticsearch.yml config and the acl's you have configured

**Comment by madhusudand** [comment] 2015-07-20 06:45
elasticsearch.yml configuration:
searchguard.enabled: true

searchguard.check_for_root: false


# The index name where Searchguard will store its configuration and various other informations related to Searchguard itself
# This index can only be access from localhost
searchguard.config_index_name: searchguard

# Enable or disable HTTP session which caches the authentication and authorization informations in a cookie
searchguard.http.enable_sessions: false

# If this is true (default is false) then allow all HTTP REST requests from nodes loopback (e.g. localhost)
searchguard.allow_all_from_loopback: true

# When using DLS or FLS and a get or mget is performed then rewrite it as search request
#searchguard.rewrite_get_as_search: true

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend

searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator

searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.settingsdb.user.admin: admin
searchguard.authentication.settingsdb.user.user1: user2
searchguard.authentication.settingsdb.user.user2: user1

searchguard.authentication.authorization.settingsdb.roles.admin: [ "admin" ]
searchguard.authentication.authorization.settingsdb.roles.user1: [ "others" ]
searchguard.authentication.authorization.settingsdb.roles.user2: [ "others" , "admin" ]

# Configure the actionrequestfilter to allow or forbid action
searchguard.actionrequestfilter.names: [ "others" ]
searchguard.actionrequestfilter.readonly.allowed_actions: [ "indices/data/read/*","*monitor*", "indices:admin*","org.elasticsearch.rest.action.cat.RestCountAction","RestCatAction"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*","indices:data/write*"]



ACL:
{"_index":"searchguard","_type":"ac","_id":"ac","_version":1,"found":true,"_source":{
    "acl": [
    {
        "__Comment__": "others: all filters are executed",
        "roles": [ "others" ],
        "filters_bypass": [],
        "filters_execute": [ "*" ]
     },
     {
           "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
           "roles": [ "admin" ],
           "filters_bypass": [ "*" ],
           "filters_execute": []
     },
     {
           "__Comment__": "default no filter no bypass",
           "filters_bypass": [],
           "filters_execute": []
     }
     ]
}}

**Comment by alexyiu-elementum** [comment] 2015-08-04 00:58
I ran into similar situation as well. 
Exception thrown by this line: 
https://github.com/floragunncom/search-guard/blob/master/src/main/java/com/floragunn/searchguard/filter/SearchGuardActionFilter.java#L195

This exception is thrown only when using Java Transport client only, not HTTP Client Curl, even I am using the same user id ("restrictedreader"):

~~~~~~~~~~~~~~~~~~~~~~
Caused by: java.lang.RuntimeException: Attempt from inet[/127.0.0.1:60900] to _all indices for indices:data/read/search and User [name=restrictedreader, roles=[ELS_Reader]]
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply0(SearchGuardActionFilter.java:195)
	at com.floragunn.searchguard.filter.SearchGuardActionFilter.apply(SearchGuardActionFilter.java:89)
~~~~~~~~~~~~~~~~~~~~~~

Thanks!

**Comment by alexyiu-elementum** [comment] 2015-08-04 01:38
madhusudand  ... 

Are you using Java Transport Client or HTTP Client? 

I ran into the similar situation when I forgot to put "indices" argument in Java's "prepareSearch(...)" call. 

For example: 
The following ran into the above error message:
~~~~~~~~~~~~~~~~~~~~~
client.prepareSearch().putHeader("searchguard_transport_creds", genSearchGuardCredHeaderVal(searchGuardUsername, searchGuardPassword)) ... 
~~~~~~~~~~~~~~~~~~~~~

The following works. 
~~~~~~~~~~~~~~~~~~~~~
client.prepareSearch(indices).putHeader("searchguard_transport_creds", genSearchGuardCredHeaderVal(searchGuardUsername, searchGuardPassword)) ... 
~~~~~~~~~~~~~~~~~~~~~

The above "indices" is a proper non-empty string value (e.g. "fooIndex") 

Hope this helps.

**Comment by madhusudand** [comment] 2015-08-04 07:23
@alexyiu-elementum  thanks for the reply....
I was trying to hit elasticsearch from web browser....
But anyways.. can you share me the client code for accessing elasticsearch.. if you wish to :)..

**Comment by alexyiu-elementum** [comment] 2015-08-04 18:17
I was using in Java Client code for ElasticSearch. If this is not what you want to do, sharing my code would not be useful. 

It may be easier to share the URL pattern in your Browser (its equivalent CURL command). Then, maybe, I could help you debug further.

**Comment by madhusudand** [comment] 2015-08-05 05:47
Thanks @alexyiu-elementum 
This is the URL pattern.
http://ES-HOST-IP:9200/_cat/count
equivalent CURL would be 
"curl -XGET http://ES-HOST-IP:9200/_cat/count"

**Comment by nitram4** [comment] 2015-08-26 19:41
+1 having exactly the same issue, have bash scriptnusing _cat api and could not use it because of that issue

**Comment by faxm0dem** [comment] 2016-01-12 11:44
Having same issue here, with a fresh install of `v1.7.3.0` and `elasticsearch-1.7.4`.

**Comment by floragunncom** [comment] 2016-05-01 12:21
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Closed by floragunncom** 2016-05-01 12:21 UTC
Labels: wait for user feedback
