### ISSUE TITLE
LDAP roles authorization not working as expected

### ISSUE THREAD

**Issue by vostrom** [floragunncom/search-guard#657] opened 2019-03-20 16:05 UTC
Hi!
We are using elasticsearch 6.6 and searchguard 6.6 in our company.
I have been trying to configure authorization and authentication using our ldap server with elastic (with a lot of great help in the forums).
I believe that I found why we could not get the wanted results using _dls_ and ldap roles of a user for authentication after everything was configured right.
Our ldap contains roles with Hebrew names and I believe that searchguard does not support it.

Does anyone know if this can actually pose a problem and if there can be a solution for it?

**Comment by floragunncom** [comment] 2019-03-20 16:19
Can you please attach the complete elasticsearch.yml, sg_config.yml, sg_roles_mapping.yml and a ldif file containing a few examples with Hebrew names. Pls also run sgadmin with the --diagnose switch and provide the diagnose trace file (may contain sensitive informations!, see https://docs.search-guard.com/latest/troubleshooting-sgadmin#using-the-diagnose-switch).

If you need to provide sensitive information you can send us pgp encrypted emails (see https://search-guard.com/security).

**Comment by floragunncom** [comment] 2019-03-26 06:59
@vostrom friendly ping

**Comment by vostrom** [comment] 2019-04-02 08:20
Sorry for the huge delay,
I tried to debug this on my own and I think that I was wrong before.
I think that the problem occurs due to "/" in all of our ldap cn's.
I get the following error:
`...LDAPAuthorizationException] [test_cluster] Unable to fill user roles due to org.ldaptive.LdapException: javax.naming.InvalidNameException: CN=1\2f בית ספר...`

In addition, when resolve_nested_roles is set to true, our elasticsearch blows completely (the processes  should be manually killed as the service does not respond). this happens due to loops our ldap. I've checked in the code and fixing it should be easy (I would like to open a PR if possible), although I do not know how to create a testing environment for the project.

**Comment by floragunncom** [comment] 2019-04-02 09:56
Can you point me to the code which loops? You can also post a code snippet here with your fixes included. And please attach the complete elasticsearch.yml, sg_config.yml, sg_roles_mapping.yml and a ldif file containing a few LDAP entry examples so that we can try to reproduce the issue.

**Comment by vostrom** [comment] 2019-04-02 11:44
I believe that the bug happens in the function resolveNestedRoles:
```
...
if (depth < maxDepth) {
	for (final LdapName nm : new HashSet<LdapName>(result)) {
		Set<Map.Entry<String, Settings>> nameRoleSearchBaseKeys = resultRoleSearchBaseKeys.get(nm);

		if (nameRoleSearchBaseKeys == null) {
			log.error(
					"Could not find roleSearchBaseKeys for " + nm + "; existing: " + resultRoleSearchBaseKeys);
			continue;
		}

		final Set<LdapName> in = resolveNestedRoles(nm, ldapConnection, userRoleName, depth, rolesearchEnabled,
				nameRoleSearchBaseKeys, roleFilter);
		result.addAll(in);
	}
}
...
```
Because the recursion runs until the `depth` is reached, when a loop occurs, a whole new, identical tree will be created and added to the `result`. thus, if the depth is big (default is 30...) than a loop will add the same LdapName objects ~(number_of_users_in_ldap_role)^30 which has no actual effect. 
If i'm not mistaken the simple solution will be to something like: 
```
if nm in result:
    continue
```
before the recursive call.

**Comment by floragunncom** [comment] 2019-04-02 11:48
I will have a look, thanks ...

**Comment by vostrom** [comment] 2019-04-02 12:15
Thanks!
I will try to add the yml files soon for the other bug we experienced, we are using an offline network in the company so it is not easy.

**Comment by floragunncom** [comment] 2019-04-02 16:02
Is your company already a customer or are you just testing at the moment?

**Comment by floragunncom** [comment] 2019-04-03 09:27
After digging into the code you pointed out above for resolving nested roles i cannot find an issue right now. The recursion terminates if either maxDepth is reached or if the previously found nested roles do not contain any other nested roles and so `for (final LdapName nm : new HashSet<LdapName>(result)) {` will not be executed because `result` is empty.

It would be great if you can provide ldif files (maybe anonymized or manually crafted) so i can reproduce the "looping" issue. As a workaround i suggest you reduce maxDepth to something like `2` (don't know how deep your nested roles contain other nested roles).

**Comment by floragunncom** [comment] 2019-04-14 12:07
@vostrom friendly ping

**Comment by floragunncom** [comment] 2019-07-03 15:32
Closing this due to inactivity

**Closed by floragunncom** 2019-07-03 15:32 UTC
Labels: bug
