### ISSUE TITLE
[ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [127.0.0.1] SSL Problem Received fatal alert: certificate_unknown

### ISSUE THREAD

**Issue by pribal** [floragunncom/search-guard#466] opened 2018-03-29 11:51 UTC
I am using ES 5.6.7 and searchgurad 5.6.7-19 .I am getting below error "ERR: You try to connect with a ssl node certificate instead of an admin client certificate" while running with sgadmin.sh

/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh -cd /usr/share/elasticsearch/plugins/search-guard-5/sgconfig -ks /etc/elasticsearch/node-0-keystore.jks -kspass xxxxx -ts /etc/elasticsearch/truststore.jks -tspass xxxxxx -nhnv -icl -h localhost -port 9740

And in elasticsearch log file , i am getting below error

[2018-03-29T01:12:10,795][ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [127.0.0.1] SSL Problem Received fatal alert: certificate_unknown
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

please find my elasticsearch.yml details

cluster.name: XXX_sandbox_cluster
node.name: 127.0.0.1
network.host: 127.0.0.1
transport.tcp.port: 9740
http.port: 9640
#discovery.zen.ping.unicast.hosts: ["xxxxxx"]
path.data: /data/elasticsearch
path.logs: /log/elasticsearch
script.engine.groovy.inline.aggs: on

searchguard.ssl.transport.keystore_filepath: node-0-keystore.jks
searchguard.ssl.transport.keystore_password: XXX
searchguard.ssl.transport.truststore_filepath: truststore.jks
searchguard.ssl.transport.truststore_password: XXX
#searchguard.ssl.transport.enforce_hostname_verification: false
searchguard.ssl.transport.enabled: true
searchguard.ssl.http.enabled: true
searchguard.ssl.http.keystore_filepath: node-0-keystore.jks
searchguard.ssl.http.keystore_password: XXX
searchguard.ssl.http.truststore_filepath: truststore.jks
searchguard.ssl.http.truststore_password: xxxxx
searchguard.authcz.admin_dn:
  - CN=admin,OU=SSL,O=Test,L=Test,C=DE

**Comment by pribal** [comment] 2018-03-29 12:01
I have created the new certificate and run with sgadmin.sh with no error .

/usr/share/elasticsearch/plugins/search-guard-5/tools/sgadmin.sh -cd /usr/share/elasticsearch/plugins/search-guard-5/sgconfig -ks /etc/elasticsearch/admin-keystore.jks -kspass changeit -ts /etc/elasticsearch/truststore.jks -tspass changeit -nhnv -icl -h 127.0.0.1 -port 9740

searchguard index already exists, so we do not need to create one.
Populate config from /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/
Will update 'config' with /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_config.yml
   SUCC: Configuration for 'config' created or updated
Will update 'roles' with /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_roles.yml
   SUCC: Configuration for 'roles' created or updated
Will update 'rolesmapping' with /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_roles_mapping.yml
   SUCC: Configuration for 'rolesmapping' created or updated
Will update 'internalusers' with /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_internal_users.yml
   SUCC: Configuration for 'internalusers' created or updated
Will update 'actiongroups' with /usr/share/elasticsearch/plugins/search-guard-5/sgconfig/sg_action_groups.yml
   SUCC: Configuration for 'actiongroups' created or updated
Done with success


But still error in elastic search
[2018-03-29T07:58:21,479][ERROR][c.f.s.s.t.SearchGuardSSLNettyTransport] [127.0.0.1] SSL Problem Received fatal alert: certificate_unknown
javax.net.ssl.SSLException: Received fatal alert: certificate_unknown

Can you please help me

**Comment by jochenkressin** [comment] 2018-03-29 12:03
Please do not crosspost, you have already posted on Google Groups:

https://groups.google.com/forum/#!topic/search-guard/PvIDqMr4UU0

This is not a bug but a configuration problem, so I'm closing the issue here.

**Closed by jochenkressin** 2018-03-29 12:03 UTC
