### ISSUE TITLE
SSO Authentication

### ISSUE THREAD

**Issue by athuljayaraj** [floragunncom/search-guard#88] opened 2016-02-10 10:44 UTC
Does searchguard support SSO authentication?

**Comment by djtecha** [comment] 2016-03-05 00:25
I believe you have to run nginx in the front of it. I'm in the process of trying to figure out how to get it to pass the authorization.

**Comment by floragunncom** [comment] 2016-03-05 12:27
A dedicated Backend for CAS or similar is not yet planned (we appreciate contributions here) but with the upcoming ProxyAuthentication Backend this should be possible. See https://github.com/floragunncom/search-guard/issues/100

**Comment by floragunncom** [comment] 2016-05-01 11:24
closed as duplicate of #100

**Closed by floragunncom** 2016-05-01 11:24 UTC
