### ISSUE TITLE
Search Guard not initialized (SG11) on windows

### ISSUE THREAD

**Issue by leelyliu** [floragunncom/search-guard#174] opened 2016-07-18 15:13 UTC
[ERROR][com.floragunn.searchguard.auth.BackendRegistry]
 Not yet initialized

how to write a sgadmin.bat which run on windows?

Thanks.

**Comment by floragunncom** [comment] 2016-07-18 20:44
The sgadmin.sh is merely just a wrapper for the class SearchGuardAdmin and consists of just three lines of code. It should be super-easy to port it to a .bat script. 

If you need help with that, please use the Search Guard Google Group:

https://groups.google.com/forum/#!forum/search-guard

Closing, since it's a question, not a bug.

**Closed by floragunncom** 2016-07-18 20:44 UTC

**Comment by floragunncom** [comment] 2016-10-19 21:34
.bat files added by https://github.com/floragunncom/search-guard/commit/5833e38278a2af623f1f86a541202b995b7e4bab
