### ISSUE TITLE
Please document precise steps to be taken after a user changes elasticsearch.yml file

### ISSUE THREAD

**Issue by cfoutstd** [floragunncom/search-guard#212] opened 2016-10-05 14:50 UTC
ES v2.3.5
SG-SSL v2.3.5.15
SG v2.3.5.5

I reported issue #211 and it was resolved/closed as "works as designed." Fair enough. However I'm still having issues starting Elasticsearch when, in my case, I change the data path. SG recommended that I rerun sgadmin.sh, which I did to no avail. Can you please document the precise steps that a user needs to take when he/she changes elasticsearch.yml file, e.g., the data path?

After you change elasticsearch.yml, do this...

- Rerun sgadmin.sh with pertinent parameters
- What else???

**Comment by jochenkressin** [comment] 2016-10-05 15:16
Hi,

if you change the data path to point to a new directory, then the only thing you need to do is to rerun sgadmin, with the same parameters as before. Since all configuration settings are stored in a Search Guard index on your ES cluster, this index needs to get repopulated.  Let's say you stopped your cluster, changed the data directory, and started the cluster again. The just rerun sgadmin and everything should be fine.

If this does not work for you, please describe what happens when you rerun sgadmin, and post a log file with Search Guard on debug level, so we can reproduce the behaviour:

  com.floragunn: DEBUG
(in: logging.yml)

Also, please update the SG version to at least 2.3.5.6. Versions before that had a bug where the SG index was not found under certain conditions.

**Comment by cfoutstd** [comment] 2016-10-05 15:39
I did the following:
- Stopped ES
- Removed current SG v2.3.5.5 plugin
- Installed SG v2.3.5.7
- Updated data path in elasticsearch.yml
- Started ES, got log stating to run sgadmin.sh

```
[2016-10-05 15:27:50,256][INFO ][com.floragunn.searchguard.action.configupdate.TransportConfigUpdateAction] [ip-10-22-9-4] searchguard index does not exist yet, so no need to load config on node startup. Use sgadmin to initialize cluster
```
- Issued sgadmin.sh, and got following exceptions

```
[2016-10-05 15:28:58,408][INFO ][cluster.metadata         ] [ip-10-22-x-x] [searchguard] creating index, cause [api], templates [], shards [1]/[0], mappings []
[2016-10-05 15:28:58,461][WARN ][indices.cluster          ] [ip-10-22-x-x] [[searchguard][0]] marking and sending shard failed due to [failed to create shard]
java.lang.NullPointerException
	at org.elasticsearch.index.shard.ShardPath.selectNewPathForShard(ShardPath.java:241)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:336)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:601)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:501)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:166)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
[2016-10-05 15:28:58,465][WARN ][cluster.action.shard     ] [ip-10-22-x-x] [searchguard][0] received shard failed for target shard [[searchguard][0], node[69B9g_xHQL2KpeQLGgQxPg], [P], v[1], s[INITIALIZING], a[id=lDau69e_SMqHJZ0fvxXAKQ], unassigned_info[[reason=INDEX_CREATED], at[2016-10-05T15:28:58.410Z]]], indexUUID [gluSfkB4TB-Wa5D5yRlizQ], message [failed to create shard], failure [NullPointerException[null]]
java.lang.NullPointerException
	at org.elasticsearch.index.shard.ShardPath.selectNewPathForShard(ShardPath.java:241)
	at org.elasticsearch.index.IndexService.createShard(IndexService.java:336)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyInitializingShard(IndicesClusterStateService.java:601)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.applyNewOrUpdatedShards(IndicesClusterStateService.java:501)
	at org.elasticsearch.indices.cluster.IndicesClusterStateService.clusterChanged(IndicesClusterStateService.java:166)
	at org.elasticsearch.cluster.service.InternalClusterService.runTasksForExecutor(InternalClusterService.java:610)
	at org.elasticsearch.cluster.service.InternalClusterService$UpdateTask.run(InternalClusterService.java:772)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.runAndClean(PrioritizedEsThreadPoolExecutor.java:231)
	at org.elasticsearch.common.util.concurrent.PrioritizedEsThreadPoolExecutor$TieBreakingPrioritizedRunnable.run(PrioritizedEsThreadPoolExecutor.java:194)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

```

**Comment by jochenkressin** [comment] 2016-10-05 15:43
Thanks for the logs, this should not happen, we're investigating.

**Comment by cfoutstd** [comment] 2016-10-05 15:50
Thank YOU for helping. I just wanted to add that if I comment out the path.data line in elasticsearch.yml, and stop/start ES, then run sgadmin.sh, it works.

**Comment by floragunncom** [comment] 2016-10-05 18:39
You hit https://github.com/elastic/elasticsearch/pull/19554 i think

**Comment by floragunncom** [comment] 2016-10-05 18:40
Close this issue because its very likely not a SG bug

**Closed by floragunncom** 2016-10-05 18:40 UTC
