### ISSUE TITLE
[WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:admin/exists (class org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest) due to type[s]() method not found

### ISSUE THREAD

**Issue by julienbeclin** [floragunncom/search-guard#16] opened 2015-06-24 09:35 UTC
Hello,

Not really an issue, just a warn.
I keep seeiing this warning appear when I login with a user : 

```
[WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:admin/exists (class org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest) due to type[s]() method not found
```

Any idea what it is ?
Thanks

**Comment by julienbeclin** [comment] 2015-06-24 13:46
It would really help if you could explain this warning as I have this error coming up everytime I try something new : 

```
[2015-06-24 15:41:39,034][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:admin/exists (class org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest) due to type[s]() method not found
[2015-06-24 15:41:39,139][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] actionrequestfilter.readonly Action 'indices:admin/exists' is forbidden due to DEFAULT
[2015-06-24 15:41:39,158][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.RuntimeException: Action 'indices:admin/exists' is forbidden due to DEFAULT for action indices:admin/exists
java.lang.RuntimeException: Action 'indices:admin/exists' is forbidden due to DEFAULT
```

Thanks !

**Comment by floragunncom** [comment] 2015-06-25 13:08
This means that if you have configured types in your acl this would be ignored for the above request cause no type information is associated with the request (which is natural for 'indices:admin/exists'). If you have not configured types you can safely ignore this warning.

**Comment by julienbeclin** [comment] 2015-06-25 13:35
Just to be sure, by "type" you mean "filter type" ? Like for example the readonlyfilter you configured in your example ? 
The issue is that an error occurs because of this.

**Comment by floragunncom** [comment] 2015-06-25 13:39
no, i mean types which live inside an index (https://www.elastic.co/guide/en/elasticsearch/guide/current/_document_metadata.html) in terms of _type or class of object

**Comment by julienbeclin** [comment] 2015-06-25 13:41
Oh ok, that's why I get this warning, because I did configure types on some index

**Comment by floragunncom** [comment] 2015-06-25 13:59
pls post your acl

**Comment by julienbeclin** [comment] 2015-06-25 14:02
Config :

```json
# Configure the actionrequestfilter to allow or forbid action 
searchguard.actionrequestfilter.names: ["readonly"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*", "indices:admin*", "indices:data/write*"]

# Configure document level security (dls) filter
searchguard.dlsfilter.names: ["dashboard","index-pattern"]
searchguard.dlsfilter.dashboard: ["term", "title","Dashboard logs", "false"] # if field==value (or not) match
searchguard.dlsfilter.index_pattern: ["term", "index-pattern","logstash-*", "false"] # if field==value (or not) match
```

and this acl rule : 

```json
    {
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": ["*"]
    },

    {
    "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
    "roles": ["admin"],
    "filters_bypass": ["*"],
    "filters_execute": []
    },

    {
      "__Comment__": "Any authenticated user can do anything on the '.kibana' index - no filter will be executed",
      "indices": [".kibana"],
      "filters_bypass": ["*"],
      "filters_execute": []
    },

    {
       "__Comment__": "user1 has document level filter set for index_pattern",
       "users": ["user1"],
       "indices": [".kibana"],
       "filters_bypass": [],
       "filters_execute": ["dls.dashboard"]
}

**Comment by julienbeclin** [comment] 2015-06-25 14:03
What I am trying to do is give access to my ".kibana" index to all users and then filter on other index to control access to data and filter on index-pattern, visualisation and dashboards (which are different _type of the .kibana index) to control access to visualtisations and dashboard !

**Comment by floragunncom** [comment] 2015-06-25 14:04
you have no types configured in your acl (this would look like <code>"indices": ["index:type"]</code>) so you can ignore this warning

**Comment by floragunncom** [comment] 2015-06-25 14:07
the last rule from https://github.com/floragunncom/search-guard/issues/16#issuecomment-115268560 has no effect because the second last rule allows all for .kibana index

**Comment by julienbeclin** [comment] 2015-06-25 14:18
Oh yes indeed, this config must be giving access to kibana but not doing any filter on index (I tried multiple different configs).
My main issue is how to give read and get access to kibana server and then filter on _types ? Because the only way I am able to give access to kibana for a user is to write bypass : ["true"] in my acl rule, which then bypass all dlsfilter or flsfilter

**Comment by julienbeclin** [comment] 2015-06-25 14:26
Ok so this means if I put : 

```json
{
      "__Comment__": "Any authenticated user can do anything on the '.kibana' index with  _type:dashboard - no filter will be executed",
      "indices": [".kibana:dashboard"],
      "filters_bypass": ["*"],
      "filters_execute": []
    }
```

**Comment by julienbeclin** [comment] 2015-06-25 15:00
All right so : 

My config : 
```json
# Enable or disable the complete Searchguard plugin functionality
searchguard.enabled: false

# Path where to write/read the searchguard master key file
searchguard.key_path: /etc/searchguard/

# When using DLS or FLS and a get or mget is performed then rewrite it as search request
searchguard.rewrite_get_as_search: true

searchguard.authentication.authentication_backend.impl: com.floragunn.searchguard.authentication.backend.simple.SettingsBasedAuthenticationBackend

searchguard.authentication.authorizer.impl: com.floragunn.searchguard.authorization.simple.SettingsBasedAuthorizator

searchguard.authentication.http_authenticator.impl: com.floragunn.searchguard.authentication.http.basic.HTTPBasicAuthenticator

searchguard.authentication.settingsdb.user.julienkibana: 91lpdsketf13
searchguard.authentication.settingsdb.user.user1: user1mdp
searchguard.authentication.settingsdb.user.user2: user2mdp

searchguard.authentication.authorization.settingsdb.roles.julienkibana: ["admin"]

# Configure the actionrequestfilter to allow or forbid action
searchguard.actionrequestfilter.names: ["readonly","kibanaaccess"]
searchguard.actionrequestfilter.readonly.allowed_actions: ["indices:data/read/*", "*monitor*"]
searchguard.actionrequestfilter.readonly.forbidden_actions: ["cluster:admin*","indices:admin*","indices:data/write*"]
```

My acl rules : 

```
{"acl": [
{
      "__Comment__": "Default is to execute all filters",
      "filters_bypass": [],
      "filters_execute": ["*"]
    },

    {
    "__Comment__": "For role *admin* all filters are bypassed (so none will be executed). This means unrestricted access.",
    "roles": ["admin"],
    "filters_bypass": ["*"],
    "filters_execute": []
    },

    {
      "__Comment__": "Any authenticated user can do anything on the .kibana index - no filter will be executed",
      "indices": [".kibana:config",".kibana:search",".kibana:visualization",".kibana:dashboard"],
"filters_bypass": ["*"],
      "filters_execute": []
    }
]}
```

My error : 
```json
[2015-06-25 16:56:27,103][INFO ][com.floragunn.searchguard.rest.DefaultRestFilter] Authenticated user is User [name=user1, roles=[]]
[2015-06-25 16:56:27,115][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] Cannot determine types for indices:admin/exists (class org.elasticsearch.action.admin.indices.exists.indices.IndicesExistsRequest) due to type[s]() method not found
[2015-06-25 16:56:27,119][WARN ][com.floragunn.searchguard.filter.SearchGuardActionFilter] actionrequestfilter.readonly Action 'indices:admin/exists' is forbidden due to indices:admin*
[2015-06-25 16:56:27,128][ERROR][com.floragunn.searchguard.filter.SearchGuardActionFilter] Error while apply() due to java.lang.RuntimeException: Action 'indices:admin/exists' is forbidden due to indices:admin* for action indices:admin/exists
java.lang.RuntimeException: Action 'indices:admin/exists' is forbidden due to indices:admin*
```

**Comment by floragunncom** [comment] 2015-07-01 13:21
seems to be duplicate of https://github.com/floragunncom/search-guard/issues/19

**Comment by floragunncom** [comment] 2016-05-01 11:09
Auto close this issue because it refers to Search Guard 1 which is decommissioned now. For details pls. see https://github.com/floragunncom/search-guard-attic/wiki . If this issue is still valid for Search Guard 2 (for elasticsearch 2.x) feel free to reopen it (or to file a new one). Pls. do not longer report issues for Search Guard 1 (for elasticsearch 1.x). We sincerely apologize for the inconvenience this may have caused. Thanks for contributing!

**Closed by floragunncom** 2016-05-01 11:09 UTC
Labels: duplicate, wait for user feedback
