### ISSUE TITLE
SG_admin warnings 

### ISSUE THREAD

**Issue by iahmad-khan** [floragunncom/search-guard#516] opened 2018-07-02 14:33 UTC
Elasticsearch Version: 6.3.0
Search Guard Version: 6.3.0-22.3

Error messege:

```
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by io.netty.util.internal.ReflectionUtil (file:/usr/share/elasticsearch/plugins/search-guard-6/netty-common-4.1.16.Final.jar) to constructor java.nio.DirectByteBuffer(long,int)
WARNING: Please consider reporting this to the maintainers of io.netty.util.internal.ReflectionUtil
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Elasticsearch Version: 6.3.0
Search Guard Version: 6.3.0-22.3
```

**Comment by floragunncom** [comment] 2018-07-04 20:49
Closing this as duplicate of #514

**Closed by floragunncom** 2018-07-04 20:49 UTC
Labels: duplicate
