### ISSUE TITLE
ES 2.2 and SG "Search Guard not initialized"

### ISSUE THREAD

**Issue by djtecha** [floragunncom/search-guard#95] opened 2016-02-29 23:04 UTC
I cannot for the life of me get past running the sgadmin.sh script. I keep getting the error that SG is not initialized.

`Connect to localhost:9300
Exception in thread "main" ElasticsearchException[Search Guard not initialized (SG11) for cluster:monitor/health]
	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:240)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:99)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:45)
`

**Comment by djtecha** [comment] 2016-02-29 23:06
Here is my ES yaml file:

`#searchguard
security.manager.enabled: false
searchguard.authcz.admin_dn:
  - cn=test-2, ou=client, L=Test, C=DE
#Searchguard keys
searchguard.ssl.transport.keystore_filepath: keys/test-2-keystore.jks
searchguard.ssl.transport.truststore_filepath: keys/truststore.jks
searchguard.allow_all_from_loopback: true
`

ES appears to find and load the keys fine but every trying to this http://localhost:9200 returns the same SG error about it not be initialized.

**Comment by benejo** [comment] 2016-03-01 03:37
I am getting the same error with ES2.2 and SG2 on a different action(indices:admin/exists). Pasting below the stack trace, kindly help

Exception in thread "main" ElasticsearchException[Search Guard not initialized (SG11) for indices:admin/exists]
	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:240)
	at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:99)
	at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:45)
	at org.elasticsearch.action.support.HandledTransportAction$TransportHandler.messageReceived(HandledTransportAction.java:41)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService.messageReceivedDecorate(SearchGuardSSLTransportService.java:137)
	at com.floragunn.searchguard.transport.SearchGuardTransportService.messageReceivedDecorate(SearchGuardTransportService.java:222)
	at com.floragunn.searchguard.ssl.transport.SearchGuardSSLTransportService$Interceptor.messageReceived(SearchGuardSSLTransportService.java:107)
	at org.elasticsearch.transport.netty.MessageChannelHandler.handleRequest(MessageChannelHandler.java:244)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.handleRequest(SearchGuardMessageChannelHandler.java:57)
	at org.elasticsearch.transport.netty.MessageChannelHandler.messageReceived(MessageChannelHandler.java:114)
	at com.floragunn.searchguard.ssl.transport.SearchGuardMessageChannelHandler.messageReceived(SearchGuardMessageChannelHandler.java:45)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.elasticsearch.common.netty.OpenChannelsHandler.handleUpstream(OpenChannelsHandler.java:75)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:296)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.unfoldAndFireMessageReceived(FrameDecoder.java:462)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.callDecode(FrameDecoder.java:443)
	at org.jboss.netty.handler.codec.frame.FrameDecoder.messageReceived(FrameDecoder.java:303)
	at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:70)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
	at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:559)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:268)
	at org.jboss.netty.channel.Channels.fireMessageReceived(Channels.java:255)
	at org.jboss.netty.channel.socket.nio.NioWorker.read(NioWorker.java:88)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.process(AbstractNioWorker.java:108)
	at org.jboss.netty.channel.socket.nio.AbstractNioSelector.run(AbstractNioSelector.java:337)
	at org.jboss.netty.channel.socket.nio.AbstractNioWorker.run(AbstractNioWorker.java:89)
	at org.jboss.netty.channel.socket.nio.NioWorker.run(NioWorker.java:178)
	at org.jboss.netty.util.ThreadRenamingRunnable.run(ThreadRenamingRunnable.java:108)
	at org.jboss.netty.util.internal.DeadLockProofWorker$1.run(DeadLockProofWorker.java:42)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by floragunncom** [comment] 2016-03-02 18:29
@djtecha @benejo so both of you have successfully runned sgadmin.sh and after this you get the above mentioned errors. Right?

**Comment by djtecha** [comment] 2016-03-02 22:21
No, for me the initial sgadmin.sh fails with that. Not sure how I'm supposed to initialize as I thought that script did it.

**Comment by benejo** [comment] 2016-03-03 06:41
Same for me, the sgadmin.sh script fails with the above mentioned error.

**Comment by benejo** [comment] 2016-03-03 06:45
# plugins/search-guard-2/tools/sgadmin.sh -h 10.200.0.11 -cd plugins/search-guard-2/sgconfig/ -ks plugins/search-guard-2/sgconfig/elkadmin-keystore.jks -kspass password1 -ts plugins/search-guard-2/sgconfig/truststore.jks -tspass password2
Connect to 10.200.0.11:9300
[06:40:25,731][WARN ] org.elasticsearch.com.floragunn.searchguard.ssl.SearchGuardKeyStore - AES 256 not supported, max key length for AES is 128. To enable AES 256 install 'Java Cryptography Extension (JCE) Unlimited Strength Jurisdiction Policy Files'
Exception in thread "main" ElasticsearchException[Search Guard not initialized (SG11) for indices:admin/exists]
	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:240) at org.elasticsearch.action.support.TransportAction$RequestFilterChain.proceed(TransportAction.java:99) at org.elasticsearch.action.support.TransportAction.execute(TransportAction.java:77)

**Comment by floragunncom** [comment] 2016-03-03 10:06
Pls. make sure that elasticsearch.yml contains an entry like
<pre>
searchguard.authcz.admin_dn:
  - "cn=xxx, ou=yyy, L=Test, C=DE"
# note the double quotes above !!
</pre>

where "cn=xxx, ou=yyy, L=Test, C=DE" matches your DN of the certificate you submit via

<pre>
sgadmin.sh -ks keystore.jks
</pre>

**Comment by benejo** [comment] 2016-03-03 12:58
I ran the clean.sh to delete all the certs and tried again with double quotes and made sure the cn mentioned in ES config matches the keystore used for sgadmin.sh. This time I got the same error(action cluster:monitor/health) as djtecha got. Pasting below a short stacktrace,

Exception in thread "main" ElasticsearchException[Search Guard not initialized (SG11) for cluster:monitor/health]
	at com.floragunn.searchguard.filter.SearchGuardFilter.apply(SearchGuardFilter.java:240)

**Comment by djtecha** [comment] 2016-03-03 17:38
Here is my ES config, could it be I have some network stuff off? I can connect to 9300 though from the loacl box (where the script is run from as well).


`cluster.name: elasticsearch
node.name: "corp-estest-2"
node.master: "true"
node.rack: "HQ"
node.max_local_storage_nodes: 1
index.number_of_shards: 5
index.number_of_replicas: 0
path.conf: /etc/elasticsearch
path.data: /data 
discovery.zen.minimum_master_nodes: 0

network.bind_host: "0.0.0.0"
network.publish_host: _non_loopback:ipv4_
discovery.zen.ping.multicast.enabled: false
discovery.zen.ping.unicast.hosts: ["corp-estest-2"]

security.manager.enabled: false
searchguard.authcz.admin_dn:
  - "cn=corp-estest-2, ou=client, L=Test, C=DE"
searchguard.ssl.transport.keystore_filepath: keys/corp-estest-2-keystore.jks
searchguard.ssl.transport.truststore_filepath: keys/truststore.jks
searchguard.allow_all_from_loopback: true
`

**Comment by floragunncom** [comment] 2016-03-03 18:33
Can you pls. post the logs (on debug level, after you faced this error)?

**Comment by floragunncom** [comment] 2016-03-03 18:35
oh, maybe this helps: https://groups.google.com/d/msgid/search-guard/f2d45829-6759-45f8-bbdd-43ca50d85890%40googlegroups.com

**Comment by djtecha** [comment] 2016-03-03 19:08
Woot! Got it running!

To the rest this is what I did:

run `openssl x509 -noout -subject -in corp-estest-2-signed.pem -text` to grab the CN info, then make sure it's in the following format.

searchguard.authcz.admin_dn:
  - "CN=corp-estest-2,OU=client,O=client,L=Test,C=DE"

**Comment by floragunncom** [comment] 2016-03-03 19:09
will try to make this less hard ...

**Comment by djtecha** [comment] 2016-03-03 19:10
Haha I think adding this combined with all the ES 2.2 changes complicates things. I really appreciate your hard work!

**Comment by floragunncom** [comment] 2016-03-13 15:41
So to summarize here:
* `cn=corp-estest-2, ou=client, L=Test, C=DE` != `"CN=corp-estest-2,OU=client,O=client,L=Test,C=DE"`
* Be careful to specify `searchguard.authcz.admin_dn` correct and if its not working double check: https://github.com/floragunncom/search-guard/issues/95#issuecomment-191917938

`searchguard.authcz.admin_dn` is case in-sensitive but the RDN's must be in the right order.
* `"CN=corp-estest-2,OU=client,O=client,L=Test,C=DE"` == `"cn=COrp-estest-2, OU=client,o=Client, L=Test,  C=DE"`
* `"CN=corp-estest-2,OU=client,O=client,L=Test,C=DE"` != `"CN=corp-estest-2,OU=client,O=client,C=DE,L=Test"`

Will close this. Feel free to reopen.

**Closed by floragunncom** 2016-03-13 15:41 UTC

**Comment by amirkrasnic** [comment] 2016-05-03 16:18
I am now trying for almost 3 weeks and cannot resolve this problem. When I create a keystore and truststore with the given example scripts from search-guard-ssl plugin, I set the DN to 
`"CN=node-0.example.com, OU=SSL, O=Test, L=Test, C=DE"`
and everything works like a charm. But the keystore is created with a self-signed certificate and I need a trusted one.
So, I have a trusted wildcard-certificate and I created a keystore and truststore from it to distribute to my node. But when I want to apply the config with that one, I get the _Search-Guard not initialized_ error.
The DN of my own Keystore looks like this:
`"CN=*.company.de, OU=companyunit, O=company GmbH, L=somecity, ST=region, C=DE"`.
I hope you can help because I'm going crazy with this.

**Comment by floragunncom** [comment] 2016-05-03 16:44
Please provide more informations about how you create the key- and truststores (a script or openssl/keytool commands and elasticsearch.yml) and the error message you got as well as your Search Guard SSL and Elasticsearch version.

The example skripts, to be precise, does not create self-signed certificates but they create a real certificate authority and sign the created certificates whit that CA. They show the necessary steps you need to do to generate valid set of certificates.

Which CA do you use? A official one like Verisign/Symantec or a own CA from you company?
Did you create a certificate signing request? Did you configure ``searchguard.authcz.admin_dn``in elasticsearch.yml properly?

**Comment by amirkrasnic** [comment] 2016-05-03 18:10
Thank you for the fast response.
I use Search-guard-ssl version 2.3.1.8.1 and search-guard version 2.3.1.0-beta1.
I use official CA certificate from GlobalSign. Here is my shell to create my own keystore:
<pre>
# creating pem files from DER certificates
openssl x509 -inform DER -outform PEM -in Root-R1.crt -out Root-R1.pem
openssl x509 -inform DER -outform PEM -in gsorganizationvalg2.crt -out gsorganizationvalg2.pem

# putting all pem files to chain file
cat Root-R1.pem gsorganizationvalg2.pem GlobalSign-Organization-Validation-CA-SHA256-G2.cer > combined.pem

# creating truststore
keytool -importcert -file combined.pem -keystore truststore.jks -storepass mypass -noprompt -alias root-ca

# creating p12 keystore
openssl pkcs12 -export -in company.de.certificate.crt -inkey company.private.key -chain -CAfile combined.pem -name "node.company.de" -passout pass:mykeypass -out my.p12

# converting p12 to jks keystore
keytool -importkeystore -deststorepass mykeypass-srcstorepass mykeypass-destkeystore node-keystore.jks -srckeystore my.p12 -srcstoretype PKCS12
</pre>

my elasticsearch.yml:
<pre>
#####################################
#          elasticsearch            #
#####################################

network.host: 0.0.0.0

cluster.name: elasticsearch
node.name: int
bootstrap.mlockall: true
http.cors.allow-origin: "/.*/"
http.cors.enabled: true
index.refresh_interval: 30s


#####################################
#      search guard ssl configs     #
#####################################

# Relative path to the keystore file (mandatory, this stores the server certificates), must be placed under the config/ dir
searchguard.ssl.transport.keystore_filepath: node-keystore.jks

# Keystore password (default: changeit)
searchguard.ssl.transport.keystore_password: mykeypass

# Relative path to the truststore file (mandatory, this stores the client/root certificates), must be placed under the config/ dir
searchguard.ssl.transport.truststore_filepath: truststore.jks

# Truststore password (default: changeit)
#searchguard.ssl.transport.truststore_password: mypass

# Enforce hostname verification (default: true)
searchguard.ssl.transport.enforce_hostname_verification: false


#searchguard.ssl.transport.http.enforce_clientauth: false



#######   https   ######

# Enable or disable rest layer security - https, (default: false)
searchguard.ssl.http.enabled: true

# Relative path to the keystore file (this stores the server certificates), must be placed under the config/ dir
searchguard.ssl.http.keystore_filepath: node-keystore.jks

# Keystore password (default: changeit)
searchguard.ssl.http.keystore_password: mykeypass


# Relative path to the truststore file (this stores the client certificates), must be placed under the config/ dir
searchguard.ssl.http.truststore_filepath: truststore.jks


# Truststore password (default: changeit)
searchguard.ssl.http.truststore_password: mypass

#####################################
#       search guard configs        #
#####################################

security.manager.enabled: false
searchguard.authcz.admin_dn:
  - "CN=*.company.de, OU=companyunit, O=company GmbH, L=somecity, ST=region, C=DE"

# test admin_dn
#  - "CN=node-0.example.com, OU=SSL, O=Test, L=Test, C=DE"

</pre>

I hope this helps

**Comment by rocky4bmw** [comment] 2016-07-27 19:29
I followed same steps as per link 
https://github.com/floragunncom/search-guard/wiki/Search-Guard-Bundle.
When I try to start elasticsearch I get below error message

"service elasticsearch start
Starting elasticsearch: Exception in thread "main" ElasticsearchException[Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]]; nested: InvocationTargetException; nested: IllegalStateException[SearchGuardSSLPlugin must be be installed];
Likely root cause: java.lang.IllegalStateException: SearchGuardSSLPlugin must be be installed
        at com.floragunn.searchguard.SearchGuardPlugin.checkSSLPluginAvailable(SearchGuardPlugin.java:135)
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:53)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:472)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:432)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Refer to the log for complete error details."

When checked in logs I see below

[2016-07-27 14:27:49,501][WARN ][bootstrap                ] unable to install syscall filter: seccomp unavailable: CONFIG_SECCOMP not compiled into kernel, CONFIG_SECCOMP and CONFIG_SECCOMP_FILTER are needed
[2016-07-27 14:27:49,594][INFO ][node                     ] [node-1] version[2.3.3], pid[28517], build[218bdf1/2016-05-17T15:40:04Z]
[2016-07-27 14:27:49,594][INFO ][node                     ] [node-1] initializing ...
[2016-07-27 14:27:49,920][ERROR][bootstrap                ] Exception
ElasticsearchException[Failed to load plugin class [com.floragunn.searchguard.SearchGuardPlugin]]; nested: InvocationTargetException; nested: IllegalStateException[SearchGuardSSLPlugin must be be installed];
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:483)
        at org.elasticsearch.plugins.PluginsService.loadBundles(PluginsService.java:432)
        at org.elasticsearch.plugins.PluginsService.<init>(PluginsService.java:129)
        at org.elasticsearch.node.Node.<init>(Node.java:158)
        at org.elasticsearch.node.Node.<init>(Node.java:140)
        at org.elasticsearch.node.NodeBuilder.build(NodeBuilder.java:143)
        at org.elasticsearch.bootstrap.Bootstrap.setup(Bootstrap.java:178)
        at org.elasticsearch.bootstrap.Bootstrap.init(Bootstrap.java:270)
        at org.elasticsearch.bootstrap.Elasticsearch.main(Elasticsearch.java:35)
Caused by: java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:422)
        at org.elasticsearch.plugins.PluginsService.loadPlugin(PluginsService.java:472)
        ... 8 more
Caused by: java.lang.IllegalStateException: SearchGuardSSLPlugin must be be installed
        at com.floragunn.searchguard.SearchGuardPlugin.checkSSLPluginAvailable(SearchGuardPlugin.java:135)
        at com.floragunn.searchguard.SearchGuardPlugin.<init>(SearchGuardPlugin.java:53)
        ... 13 more

Can anyone help me in fixing this issue?

**Comment by floragunncom** [comment] 2016-07-27 20:41
@rocky4bmw this seems unrelated to the original issue, and the original issue is already closed. Please ask your question on the Search Guard Google Group: https://groups.google.com/forum/#!forum/search-guard
